### ISSUE TITLE
Tighten/standardize unsafe context messaging (also useful to polyfill `externally_connectible` in Firefox)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1015]
Previous discussion: https://github.com/pixiebrix/pixiebrix-extension/issues/682#issuecomment-873457915

---

The current `externalProtocol` implementation lacks the ability to know whether a message has been received at all. I have a couple of ideas to tackle this:

- use events + watch for changes of the `isDefaultPrevented` property on the dispatched event
- use a hidden transfer/queue element + MutationObserver to append messages and handle them when ready. The element would also indicate that the other part is ready to receive.
- always ping back to messages immediately and treat the lack of response as a failure, like `chrome.runtime.sendMessage` would

Also `pageScript.js` is reimplementing the same logic but via events.

I'm making some changes to the current implementation to address reliability/readability but not this issue specifically:

- https://github.com/pixiebrix/pixiebrix-extension/pull/1019

Related:

- https://github.com/pixiebrix/pixiebrix-app/issues/334
- #578 
- https://github.com/pixiebrix/pixiebrix-extension/issues/682
- Feature request on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1319168
- Current lift-based implementation: https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/externalProtocol.ts
- https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageScript/protocol.ts

**Comment by twschiller** [comment]
I'll take a look at this in more detail early this week. I think what you've written for improvements makes sense

The medium-term plan is to introduce an SDK the pages can include to communicate with PixieBrix (e.g., providing extension points to PixieBrix). That will be used on both Chrome and Firefox (because we won't be able to include them all as externally_connectible). 

Therefore, whatever we come up with needs to be flexible enough to support both the immediate and future SDK use-case

**Comment by fregante** [comment]
Moved to https://github.com/pixiebrix/webext-messenger/issues/5
