### ISSUE TITLE
Page Editor Scroll

### ISSUE THREAD

**Issue by MMirandi** [pixiebrix/pixiebrix-extension#1042]
- My Page Editor defaults to a pretty thin/narrow view
- An implication of this is that I can't see the "Add Existing" button by default 
- I know that I can drag the DevTools up to see this, but for others it may be confusing
- Let's add a Page Editor scroll

![Screen Shot 2021-08-09 at 4 32 01 PM](https://user-images.githubusercontent.com/53029699/128770464-12ef5a7e-055e-46be-84fa-9251beb45dc3.png)

**Comment by twschiller** [comment]
@MMirandi you're specifically referring to the "Inserting Button/Menu Item" pane correct? Scroll should be working for you while editing what you've places?

Relevant components: 
- http://github.com/pixiebrix/pixiebrix-extension/blob/3ae0b65f57bf4f36d5cc768ae8f7120036476fef/src/devTools/editor/panes/insert/InsertMenuItemPane.tsx#L37-L37

@BLoe I've always found scroll hard to ensure because you have to ensure a path of `height` attributes to the component you want to scroll. Happy to talk through my knowledge of relevant CSS here

**Comment by MMirandi** [comment]
@twschiller yes. When I go to add a button, this is what I see. Scroll would help me understand that there's more below the "Tip" box

![Screen Shot 2021-08-09 at 4 42 44 PM](https://user-images.githubusercontent.com/53029699/128771740-3dcc4bf1-d08e-453e-aae8-7b5f383658a2.png)

**Comment by fregante** [comment]
> you have to ensure a path of `height` attributes

We just need to avoid `height` altogether except one per "frame" (i.e. the view/window/iframe that we want to be scrollable independently of others).

I saw that there are a few `height: 100%` elements that are contributing to this issue and they can just be replaced by `min-height` if the intent is to center vertically, usually. 

Less CSS usually fixes issues. In this case I dropped a couple of `h-100` classes and added `overflow:scroll` to `.Pane2`

![gif](https://user-images.githubusercontent.com/1402241/128907126-7d245ab9-8b87-46a7-a90f-e7ee67c62ed8.gif)

**Comment by twschiller** [comment]
> I saw that there are a few height: 100% elements that are contributing to this issue

Those are likely from me trying to solve issues with scrolling the wizard content (without having the toolbar also scroll)

I don't recall any places where we've tried to vertically center pane content in the devtools

> Less CSS usually fixes issues. 

I'll definitely try this approach in the future!
