### ISSUE TITLE
RFC: switch from NPM to Yarn

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1121]
Via @BALEHOK 

**Potential benefits**
- Speed
- Command ergnomics (don't have to put `run` before non built-in commands)

**References**
- https://medium.com/@Andrew_Mc/yarn-pnp-npm-tink-and-pnpm-oh-my-720d02221b4b

My 2 cents are to stay on npm

**Comment by fregante** [comment]
> * Command ergnomics (don't have to put `run` before non built-in commands)

https://www.thorsten-hans.com/5-types-of-zsh-aliases/

```sh
alias nr="npm run"
```
```
nr build
```



> My 2 cents are to stay on npm

Same, but it's worth exploring just in case we it's much faster and less buggy. I just fear the occasional incompatibility with some package.

**Comment by fregante** [comment]
- Also mentioned in https://github.com/pixiebrix/pixiebrix-app/issues/265#issuecomment-898645086

**Comment by fregante** [comment]
I did some quick tests just for reference

## Install time

No node_modules, with lock file:

- npm install: 44s
- yarn: 26s

This speed improvement would only be useful on CI, in practice, since generally we don't reinstall from scratch locally.

## Command ergonomics

Even if we don't use yarn internally, anyone's free to use `yarn` to run npm scripts, it doesn't require a lockfile (but then again a `nr` alias is even shorter)

## npm link ergonomics

I haven't tested this because it would take longer than a few minutes, but by the looks of [`yarn link`’s docs](https://classic.yarnpkg.com/en/docs/cli/link/), there's no substantial difference between the two.

I can investigate this to see if it improves our issue:

- https://github.com/pixiebrix/pixiebrix-app/issues/265#issuecomment-898645086

**Comment by fregante** [comment]
No further comments, closing for now
