### ISSUE TITLE
Upgrade to webpack 5

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#113]
Plugin blockers:
* Extension loader plugin: https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/110

**Comment by fregante** [comment]
If there's no real HMR happening at React level, we can replace this with `web-ext run`, which:

1. Opens Firefox or Chrome at launch, by default with a fresh profile
2. Auto-installs the extension
3. Auto-reloads the extension

**Comment by twschiller** [comment]
Sure, let's give it a shot! What we're currently using doesn't support React HMR anyway (https://github.com/rubenspgcavalcante/webpack-extension-reloader)

On my environment, we'll need to be able to target a particular profile (my PixieBrix profile), since I need to test again certain sites and use some other plugins (e.g, React dev tools, etc.) during development

**Comment by fregante** [comment]
After upgrading to Webpack 5 I can also look into potentially merging as much of the configuration as possible since a lot of code is a copy-paste. Ideally we could have a single build for both browsers since they're largely compatible. Let me know if there's any specific reason to keep 2 separate browser builds.
