### ISSUE TITLE
Can't view source map using `npm run watch`

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1174]
Example of trying to set breakpoint when inspecting the page editor:

![image](https://user-images.githubusercontent.com/1879821/130548079-a6a5b796-e9a9-46b7-98ed-993a2ecbc902.png)

> Could not load content for webpack:///./src/devTools/editor/extensionPoints/trigger.tsx (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

@fregante any ideas?

**Comment by fregante** [comment]
This may be due to noSources being added back to the config in a recent PR. This halved the size of the local files and enabled possible uploads to BrowserStack without creating a custom build for them, but I suppose it just means that the sourcemaps aren’t complete. 

Can you try deleting that `noSources` line in the Webpack config?
