### ISSUE TITLE
Standardize form components

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1225]
**Triaging**
_More important than #1224 because this directly affects maintenance and usability of the Page Editor, and also we'll need to use this work in the Admin Console (app.pixiebrix.com)_

**Context**
- We use Formik for managing Formik state
- We use React Bootstrap which has controls/groups/etc. components
- We have some JSON schema-driven components/widgets/controls (see #1116)
- React Selector, our select component needs custom styling for it to show error state correctly (TODO: find where we do that in the code already)
- In some places we use horizontal form layouts, and in others we use vertical. This is generally based on the amount of horizontal vs. vertical space available
- Recently I created HorizontalFormGroup for some work I was doing, but the ergonomics are still awkward: http://github.com/pixiebrix/pixiebrix-extension/blob/6600dbb7b62b441f0f6c4165acc82d3e972ed1a8/src/options/pages/installed/ShareExtensionModal.tsx#L153-L153

**Problem**
- There's a lot of repetitive form code, especially in the Page Editor tab code: http://github.com/pixiebrix/pixiebrix-extension/blob/6600dbb7b62b441f0f6c4165acc82d3e972ed1a8/src/devTools/editor/tabs/actionPanel/FoundationTab.tsx#L38-L38
- These fields aren't properly wired up to the Formik form validation
- They also don't follow consistent standards for descriptions/accessibility etc.

**Other Considerations**
- For form performance, we need to be able to support FastField vs. useField? (Or use the custom useFastField)?
- useField has a performance bug where its `helpers` changes reference on each render

**Next Steps**
- [ ] How do other people solve this? Are there standard layouts?
- [ ] Align on standard terminology: what's a group vs. field. vs. widget vs. control
- [ ] Add the re-usable components to StoryBook
- [ ] Additional widgets/controls we need for #1188 and node based editor - click to edit component?
- [ ] ???

**Ideas**
- Provide a React context that has the form configuration (e.g., vertical vs. horizontal layout component?) That's how we control which widgets are used in the devtools in our schema-based widgets (see RendererContext, http://github.com/pixiebrix/pixiebrix-extension/blob/d788fe4aa83858a7a39df4b4f6e2905ba90f7d60/src/components/fields/blockOptions.tsx#L422-L422) 

**Related**
- https://github.com/pixiebrix/pixiebrix-extension/issues/1116
- https://github.com/pixiebrix/pixiebrix-app/issues/518

**Comment by BALEHOK** [comment]
Note on performance:
Do we have performance issues? Documentation for [FastField](https://formik.org/docs/api/fastfield) reads: `meant to be used on large forms (~30+ fields) or when a field has very expensive validation requirements`.

**Comment by twschiller** [comment]
> Do we have performance issues with Forms? 

Yes, we have issues in the page editor. The production build of the extension isn't bad. The dev build is extremely laggy when editing nested object/array fields

We do use FastField in some places (see "Other Considerations" above). There are also issues with the useField helpers changing references

We'll cover the history/context/considerations in our meeting tomorrow

**Comment by BALEHOK** [comment]
# Terminology:
- Component - a React component/functional component.
- Field - a Component that can render a form field including label, validation message, and input.
- Widget - part of a Field, a Component that renders the input

# General approach:
We build a set of Field Components that share the same Field API (field value, event handlers, etc.). Fields are pure presentational components, they are not aware of any state management context be it Formik or JSON Schema Form, see [HorizontalTextField](https://github.com/pixiebrix/pixiebrix-extension/blob/feature/1225-form-components/src/components/form/fields/HorizontalTextField.tsx). To bind a Field to a state manager we will create connectors (HOCs), see [withFormikField](https://github.com/pixiebrix/pixiebrix-extension/blob/feature/1225-form-components/src/components/form/fields/withFormikField.tsx)

First, we need to define the API.
To define the API we need to actually create Fields.
To know what Fields to create we can work on the refactoring of the existing forms, `ShareExtensionModal` being the first one, `EditPage` can be next (to bump into performance issues).

The most important part here is to define the design patterns for the Field API, Fields, and Forms while making no premature optimizations.

The next step is performance testing and optimizations where needed. By this time we should have the Fields and connectors ready. Since the connector [ideally] is a single point that binds a Field and a State manager it will be easier to apply performance tweaks related to the concrete state manager (ex. Formik).

**Comment by BLoe** [comment]
fyi - Aleksandr and I are starting [a Notion page](https://www.notion.so/pixiebrix/Forms-5aec8e5398c54392a57e036b5d1e19d6) to document this stuff in a longer-lasting format.
