### ISSUE TITLE
Workshop brick list overflow UI issues at smaller widths

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#1338]
The "Custom Bricks" list seems to pin it's `right` value to a set distance from the right window edge, and condenses more than the row width when the window is narrowed past a certain point:

![image](https://user-images.githubusercontent.com/2801308/133343283-d852f2ca-f2bd-4bc9-8076-532362c4c71b.png)

**Comment by twschiller** [comment]
Other places with this problem:
- Admin console team table
- Deployments table

This occurs in pretty much all our tables. We need to decide what we want the behavior to be, e.g., horizontal scroll (as I did with the history/audit tables in the app)

**Comment by fregante** [comment]
An immediate **visual** fix would be to place `width: fit-content` on the parent of the table

![gif](https://user-images.githubusercontent.com/1402241/133579703-79918071-fb26-4670-8a29-a72e0853e113.gif)

But this doesn't change the layout, which will still overflow its area.

Adding `overflow-x: auto` on the tables’ parents would also be a quick an easy fix, but it's not great UX. We'd probably want to make tables properly responsive. For example here instead of showing the contents in columns:

```
Amazon Card Button                 amazon          Foundation     0.0.1
@vm/amazon/cart-button
```

We'd just condense them into lines (everywhere or just on smaller screens) which can wrap as regular text:

```
Foundation: Amazon Card Button
@vm/amazon/cart-button v0.0.1 (amazon)
```
```

**Comment by twschiller** [comment]
@abdullah4244 

Could you help with the following?
- Add a paginatedTable folder in `src/components`, and copy over the PaginatedTable code from the app? (Once the resize PR has been merged in)
- Modify the [CustomBricksCard](https://github.com/pixiebrix/pixiebrix-extension/blob/b684435eb529d731be3ae04ca38e5527c5dce9b2/src/options/pages/workshop/CustomBricksCard.tsx#L92-L92) to use the PaginatedTable
- Add to storybook?

Let me know if you don't see the workshop as available to you. If you don't see it locally in your sidebar, you'll need to enable the `workshop` feature flag

**Comment by abdullah4244** [comment]
@twschiller 
https://github.com/pixiebrix/pixiebrix-extension/pull/3628
this pr is also covering this issue

**Comment by BLoe** [comment]
>We'd just condense them into lines (everywhere or just on smaller screens) which can wrap as regular text

I kind of think that rich list items with responsive design are better in general than tables for a lot of use-cases. Anything where you don't need to explicitly interact with/select the data in each column probably would look better as a richly-designed list instead of a table/grid. This might just be my opinion and bias from the mobile app design world though. 🤷
