### ISSUE TITLE
A non-serializable value was detected in an action, in the path: `register`. Value: ƒ register(key) {

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1476]
I'm seeing this issue on the options page on the `main` branch:

```
options.js:20425 A non-serializable value was detected in an action, in the path: `register`. Value: ƒ register(key) {
    _pStore.dispatch({
      type: _constants__WEBPACK_IMPORTED_MODULE_0__.REGISTER,
      key: key
    });
  } 
Take a look at the logic that dispatched this action:  {type: 'persist/PERSIST', register: ƒ, rehydrate: ƒ} 
```

cc @twschiller is this happening to anyone else? Could this be a storage migration issue? I'm available to debug it on Slack if it's just me

**Comment by twschiller** [comment]
I've seen this - I don't think it's hurting anything (which is why I didn't log it). I'll assign to @BLoe / @BALEHOK  since it has to do with some Page Editor redux state they added

In Redux you don't want to add functions/classes to the store since they're not serializable (so you can't persist them, replay events, apply middle ware to them, etc.)

**Comment by fregante** [comment]
It's likely that I won't be able to do this before 1.4.0

**Comment by twschiller** [comment]
Looks like this warning was introduced when we added the RTK Query middleware (which adds this check)

The action is coming from: https://github.com/rt2zz/redux-persist/issues/988
