### ISSUE TITLE
Fix packtracker

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1623]
- I disabled/uninstalled pack tracker for now so as to not interfere with builds
- It looks like builds were hanging because it didn't have the pack size for main (or whatever it thinks is the main branch)?

**Comment by fregante** [comment]
I [looked into a different tool](https://github.com/refined-github/refined-github/pull/5259) due to Packtracker’s apparent inactivity, this looks supported (the developer actually sent me an email during my tests) but it doesn't look as refined and maybe as useful as packtracker. I will try working on this again later, maybe there's an easy way to fix packtracker that we just haven't looked into.
