### ISSUE TITLE
Selector selection corner cases with multiple selector selector fields

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1640]
Context
- Found while QAing: https://github.com/pixiebrix/pixiebrix-extension/pull/1638

Steps to reproduce:
- Add a jquery reader to a brick
- Toggle selection mode for the property
- Add another property
- Toggle selector mode for that property (at this point, the overlay mode for both are toggled). The first one should be canceled when you select the other one
- Select something on the page
- The value gets filled in for both fields
- The overlay animation is still active

**Comment by fregante** [comment]
Probable solution (React): have a hook/component that handles the state of the global "overlay" instead of calling the messenger API directly.

Calling a "showOverlay" API should automatically stop/cancel the previous operation.

Alternatively, which is probably better from a UI standpoint, `SelectorSelectorWidget` should be a modal that blocks the whole editor until the user clicks cancel (ESC or `<Button>`)
