### ISSUE TITLE
Add quick bar extension point

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1866]
**Context**
- Context menus are annoying to navigate

**Libraries**
- Ninja Keys: https://github.com/ssleptsov/ninja-keys

**Related**
- https://www.alfredapp.com/
- https://support.apple.com/guide/mac-help/spotlight-mchlp1008/mac
- https://www.commandbar.com/

**Considerations**
- May need to register the hotkey: https://developer.chrome.com/docs/extensions/reference/commands/ so that PixieBrix can get temporary access to the page

**Related**
- #1865

**Comment by twschiller** [comment]
@fregante any idea if adding a hotkey to the manifest would result in users having to re-active the PixieBrix extension?

**Comment by fregante** [comment]
No it would not, it's not an extra permission. You can install GhostText to see the exact installation dialog of an extension with hotkeys (in short: it doesn't mention them)

**Comment by fregante** [comment]
I suppose this is mine now and I have to look into the "not implemented yet" list here: https://github.com/pixiebrix/pixiebrix-extension/pull/2095#issue-1076029135

### Regarding the keyboard shortcuts

We don't need to use `chrome.commands` because:

- This bar will only have items in it if an extension was registered for the current domain. On registration we already ask for permissions, so we'll always be able to listen to it. "Permission denied" means the brick won't run, just like most kinds of extensions.
- `chrome.commands` does not give us any control. We can't set, check, nor link to the page to set a shortcut. We'd only be limited to instructions like _"Open the extensions page, click here, click there, etc."_ We only receive a "command" event.

Disadvantages of a custom keyboard shortcut implementation:

- We need to offer a UI to register this command

I suggest we have a single/global keyboard shortcut and that it's registered to the current browser rather than the extension/brick. I'll need someone to:

- [ ] Implement a keyboard shortcut registration UI in the options. Inspiration: 


https://user-images.githubusercontent.com/1402241/145687337-62379c81-87e8-47ee-a94a-2d6a7317c167.mov



I didn't see any ready-made components for this, but maybe I didn't look well. Ideally what we use to capture this would be compatible with the library that registers the actual shortcut in the content script.

This could also be the base for:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1865

**Comment by twschiller** [comment]
Apologies for the delay, I think I somehow missed your comment. I opened a couple tickets related to the registering/configuring the shortcut:
- https://github.com/pixiebrix/pixiebrix-extension/issues/2188
- https://github.com/pixiebrix/pixiebrix-extension/issues/2189

> We don't need to use chrome.commands because:

Correct me if I'm wrong, but the main advantage of using the commands API is that triggering the Chrome command grants `activeTab` for the page like the context menu? This would allow you to use the quick bar on any page without PixieBrix having to request access to all pages?

I've added some notes/links on the https://github.com/pixiebrix/pixiebrix-extension/issues/2188 issue

**Comment by fregante** [comment]
I addressed the access/activeTab in this point:

> * This bar will only have items in it if an extension was registered for the current domain. On registration we already ask for permissions, so we'll always be able to listen to it. "Permission denied" means the brick won't run, just like most kinds of extensions.

**Comment by fregante** [comment]
Anything else to do here? I think we have specific issues for everything. I just opened:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2299
