### ISSUE TITLE
You can install a Blueprint from the Marketplace that is already installed/active

### ISSUE THREAD

**Issue by MMirandi** [pixiebrix/pixiebrix-extension#1998]
If you already installed a blueprint and it is active, perhaps it shouldn't let you install that same blueprint again.

**Comment by fregante** [comment]
I assume this has been fixed because active blueprints don't have a way to be installed again. Feel free to reopen if I'm on the wrong page

<img width="876" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/197358678-68385010-6dcb-4476-b7ff-ea5fb9a9fc2e.png">

**Comment by twschiller** [comment]
@fregante I think this occurs when you use click on a link in the public marketplace https://www.pixiebrix.com/marketplace/.  PixieBrix will take you directly to an activation screen for that blueprint. It also occurs if you click a share link someone sent you directly. (They're the same URL)

The fix is to have the Activate Blueprints screen check for if the blueprint is already installed

**Comment by fregante** [comment]
> PixieBrix will take you directly to an activation screen for that blueprint

I was looking for the link in the marketplace but did not see it, does it appear only for custom items?

**Comment by twschiller** [comment]
> I was looking for the link in the marketplace but did not see it, does it appear only for custom items?

That particular blueprint is not published in the marketplace (it's one internal for our team)

You can reproduce by:
1. Visiting https://www.pixiebrix.com/marketplace/08e1c3ab-edca-4c9a-8815-fd22bede4cb3/amazon-search-context-menu/ and activating the blueprint
2. Visiting https://www.pixiebrix.com/marketplace/08e1c3ab-edca-4c9a-8815-fd22bede4cb3/amazon-search-context-menu/ and activating the blueprint
