### ISSUE TITLE
Copy and paste entire bricks, including current config, in page editor

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2036]
Add functionality to page editor to enable easily copying and pasting entire bricks, including current config settings. Allow pasting either within the same extension OR into a separate extension.

This should be fairly simple to accomplish by just serializing the brick state into JSON and deserializing it into a new brick.

Considerations:
- Where does the copy button live on a brick?
- Where does the "paste" button live?
  - Integrate with the "plus" button in the node layout?
- Use the native clipboard? Or our own, internal "clipboard" function?
  - It's just saving some serialized JSON, so probably not hard to implement our own, but also would be neat to just use the clipboard
- Need to generate new instanceId for pasted bricks
- This is actually a great entry point for the entire world of "forking" existing bricks/extensions/blueprints
  - This is valuable for TaskUs as well currently

Clipboard vs. redux
* Clipboard
  * Would be cool to be able to paste things in other places
* Redux
  * Flexibility for other features, see that a brick is currently being copied

Other:
- Leave the issue of duplicating entire extensions separate, will be included with some of the forking/editing blueprints stuff

**Comment by fregante** [comment]
If I wanted to copy a whole brick I'd expect its icon to receive focus in order to use cmd-c, same goes when pasting using cmd-v.

I think the icon already does receive focus, but we don't have a specific style for it (i.e. we don't differentiate the "current brick" vs "the mouse just clicked on it"). This could be visually indicated by a focus ring  like this one I found, which is actually kind of the default on web forms (the focus ring is soft blue)

 ![image](https://user-images.githubusercontent.com/1402241/144695773-eb9bd470-31cf-4ba3-81b5-f2511391c937.png)

**Comment by fregante** [comment]
It is indeed already focused but it lacks a specific style. Demo of what I was referring to:


https://user-images.githubusercontent.com/1402241/144701186-234e8fa3-a552-4719-9738-4562eba4ebef.mov



```css
button {
	outline: solid 2px blueviolet;
	outline-offset: 2px;
}
```

**Comment by BLoe** [comment]
@fregante I don't think ctrl+c/v is a good user experience here. I don't think it will be discoverable enough. I'd rather have an explicit button on the brick config to copy the brick+current config, and then an explicit button in the node layout to paste in that brick between other nodes or at the end. Once this is set up, I think we could easily add ctrl+c/v later on if users ask for it.
