### ISSUE TITLE
RFC: T-shirt sizing tickets

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2075]
Let's start trying to align on rough T-shirt sizing of issue tickets. Starting with basic Small/Medium/Large sizes.

- Small
    - Bug fix, simple feature enhancement, UI/CSS tweak
    - Examples
        - #2020 
        - #2031 
- Medium
    - Decent-sized UI/UX change to an existing screen, adding functionality to an existing feature, etc.
    - Examples
        - #2001 
        - #1927 
- Large
    - Entire new feature, large architecture change
    - Examples
        - Editor node layout
        - Initial implementation of field toggling
    - How to think about splitting a Large issue into multiple tickets
        - Can we break the ticket into multiple sub-items, where each one is a valid state of the product? i.e. is the product in a usable state between changes?
        - Can we use feature flags to hide partially-implemented UI content, enabling us to break the engineering work into smaller tickets?
        - Are there any internal (non-UI) dependencies in the work that can be split out and done first (or concurrently) as separate tickets?
        - If there are no major "seams" in the task, can we at least break off something tiny, to go from an XL to a S and a L?

**Comment by twschiller** [comment]
Thanks for putting this together. I'd encourage us to include in the "Large" definition a conceptual cutoff where we'd want to split work across multiple tickets

The dimensions I think about when sizing are (with the point that it also includes testing/specification work/etc.):

- Specification work required?
- How localized is the change (e.g., number of parts of the system it impacts)
- How large is the change (e.g., lines of code, lines of configuration)
- Manual testing overhead
- Complexity of automated tests (e.g., due to mocking, etc.)
- Complexity of storybook stories (e.g., due to mocking)

The other thing I'll mention is that "Large" needs to have a maximum "size" where we split into multiple tickets
