### ISSUE TITLE
Only allow one Banner Alert at a time

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2083]
Related to https://github.com/pixiebrix/pixiebrix-extension/pull/2080

Having multiple stacked Banner alerts at a time could risk alienating or overwhelming users, especially new users. Only one Banner should be shown at a time.

If it's important that the user can see all notifications implemented by Banners, the experience for these notifications should be re-thought. For instance, perhaps we should have an "Alerts" dropdown in the navbar.

Questions - how should we think about delivering non-urgent/semi-urgent notifications?

**Comment by twschiller** [comment]
> Having multiple stacked Banner alerts at a time could risk alienating or overwhelming users, especially new users. Only one Banner should be shown at a time.

I agree the multiple banners is a bad experience. Thinking through them though, I think a new user would have at most 1 banner? And an existing user would have at most 2 banners?

1. Environment (developers-only)
2. Update PixieBrix (wouldn't show for new users b/c they'd always have the latest version)
3. Deployment activation (enterprise-only, so the user wouldn't also be getting invitations)
4. Invitation (individual, SMB users)

If no. 2 and no. 3 both apply, I could see showing no. 3 since during activation it will prompt the user to update PixieBrix if they have to to install the new blueprints

Is there one I'm missing here? From watching people screen share the tools, they don't notice the banners. My worry with an alerts dropdown is that it'd be even more hidden

**Comment by twschiller** [comment]
Closing for now, will re-open if we identify as an issue during UX review
