### ISSUE TITLE
Running brick in broadcast mode takes 4+ seconds

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2191]
**Steps to Reproduce**
- Have 6 tabs open, 3 of which have PixieBrix active
- Create a flow like the following
- Click the button
- The confetti takes 4+ seconds to appear

![image](https://user-images.githubusercontent.com/1879821/146682174-38cbf55f-fad8-4605-b4a7-d80345b7f97b.png)

The RUN_BRICK subcall for each tab is attempting 11 times:
![image](https://user-images.githubusercontent.com/1879821/146682216-47750fe2-8771-441a-8ac9-f2ac390684b4.png)

Investigation
- Should only be getting called on tabs PixieBrix thinks is ready:  http://github.com/pixiebrix/pixiebrix-extension/blob/3b15b511dee8d67510a9f642f598de8df236210f/src/background/executor.ts#L143-L143 (edited)

**Comment by fregante** [comment]
> The RUN_BRICK subcall for each tab is attempting 11 times:

That shouldn't affect the time it takes because those targets just don't exist. I'm not sure how it worked before, but probably a similar behavior existed but was silent.

Retrying is done:

- to wait until the content script is ready
- to wait until a named target is created and becomes ready

I think currently this retry time is around 4-5s. We can reduce the noise by limiting the broadcast to tabs we actually have access to rather than "all tabs".



> * The confetti takes 4+ seconds to appear

Can you retry with a non-development version? During development the bundles weigh 15MB due to the lack of minification and the addition of inline sourcemaps.

**Comment by fregante** [comment]
> * Should only be getting called on tabs PixieBrix thinks is ready:

That may be already happening, but I think that array isn't updated? So visiting a permitted host and then navigating away, still leaves the "tab ready" mark in that array if I remember correctly.

**Comment by twschiller** [comment]
> That may be already happening, but I think that array isn't updated? So visiting a permitted host and then navigating away, still leaves the "tab ready" mark in that array if I remember correctly.

Correct, we aren't removing tabs from tabReady on 1) full navigation, 2) closing the tab. So the tabReady just accumulates a bunch of stale information we then try to message

The good news is that the retry time is constant (or relatively constant) w.r.t. number of outdated tabs

**Comment by twschiller** [comment]
I confirmed that the delay is also present in 1.4.10

**Comment by fregante** [comment]
Interesting! So that excludes https://github.com/pixiebrix/pixiebrix-extension/pull/2090

I opened a few relates tickets, but I don’t think they're directly related to this problem. https://github.com/pixiebrix/pixiebrix-extension/issues/2193 would reduce noise and potentially allow me to drop a lot of "tab ready" code, so it's worth doing soon anyway.

**Comment by fregante** [comment]
I'm not seeing a huge delay in executing, maybe less than half a second. The only issue is that it _does_ take 3.3 seconds for the action to complete since the background handler  still has to wait for the retries to end before responding. This is the log in the origin tab:

<img width="560" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/146768912-b8d9d1b7-a097-4af1-893e-4e5774c30f9f.png">


https://user-images.githubusercontent.com/1402241/146768776-931a5ad3-612c-4ff3-bbcf-4f002a58086d.mov


I'll fix:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2193
