### ISSUE TITLE
Field toggling: clicking omitted field should put it into edit mode

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2194]
**Context**
- Currently to provide a value for an omitted field you have click the toggle and select the value then focus the input
- It would be nice to provide a value by clicking on the ommitted field. Perhaps instead of a disabled input we should a div that says "No value provided. Click to provide a value" in muted text

**Comment by twschiller** [comment]
@BLoe this might be a quick v3 usability win

**Comment by BLoe** [comment]
I'm not sure that I want to try and infer how the `Omit` option should look based on what other options are available... That seems tricky and complicated right now. The idea of clicking it and it turns into an input means we have to know which kind of input to turn it into, based on other options available. Then, what about something like `jq` data input that accepts anything? What do we show there?

**Comment by BLoe** [comment]
Also, the omit option should only ever appear as the default when there is not a default value set in the input schema. Otherwise the user has to intentionally toggle over to omit. If there are cases where a brick is defaulting to omit and it makes it annoying to toggle it every time, then I think the better fix might be to add a default to the input schema of the brick itself.

**Comment by BLoe** [comment]
Discussed IRL with Todd, we can convert to `var` input mode on click since every input should support `var`.
