### ISSUE TITLE
v2 to v3 upgrade of fields with `enum`

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2305]
Discussion: https://github.com/pixiebrix/pixiebrix-extension/pull/2298#issuecomment-1007002250

**Comment by BLoe** [comment]
Continuing the discussion from that PR, the page editor currently supports `select` and `variable` input toggle options for `enum` fields. It doesn't currently support template strings. I think we have at least two options here:

1. Start supporting template strings in page editor select inputs
  a. Update `SchemaSelectWidget` to set expression values in it's change handler
  b. No further changes needed to the upgrade logic, since the string values will currently be converted to mustache template or variable expression
2. Change upgrade logic to look for `enum` and/or `examples` in the field schema, and then write out variable expressions if the value matches, otherwise write out the raw strings. If there exist any current extensions configured in the workshop to use a template string for the select value here, it won't really work properly in the v3 runtime since we'll have written it as a raw string value. This option is somewhat less work though.

**Comment by twschiller** [comment]
Let's try to tease out the:
1. v3 toggling behavior (for new extensions)
2. v2 to v3 upgrade

## Considerations
- The behavior of the page editor of the runtime execution. In the runtime, expressions are evaluated/rendered before validation against the `enum` in the schema
- What does the select widget currently produce for new bricks? It produces literal string, number, etc. values, correct?

## Schemas to consider

The "desired" is what I would expect?

**string with enum**

Current options: select (literal), variable expression
Desired options: select (literal), variable expression, template expression

```
type: string
enum: ["foo", "bar"]
```

**number with enum**

Current/Desired options: select (literal), variable expression

```
type: number
enum: [1, 2, 3]
```

**string with examples**

Current options: select (literal with create), variable expression
Desired options: select (literal with create), variable expression, template expression

```
type: string
examples: ["foo", "bar"]
```

**number with examples**

Current/Desired options: select (literal with create), variable expression

```
type: string
examples: ["foo", "bar"]
```

## Discussion

> Start supporting template strings in page editor select inputs

How would this proposal work for numbers? For string it would produce an expression object, but for numbers it would produce a literal?

How would the select handle `{{ @input.foo }}-1` since that template expression wouldn't be in the list of enums? Would we need to support createable in all cases? 

>  Change upgrade logic to look for enum and/or examples in the field schema, and then write out variable expressions if the value looks like a variable, otherwise write out the raw strings.

This is what I would propose. To do this we would just need to look for:
1. Strings that follow the `@identifier` pattern. (I think our upgrade logic already does this)
2. Strings that contain `{{` or `{%`, as they are most certainly template expressions

 >  If there exist any v2 extensions configured in the workshop to use a template string for a select value, it won't really work properly in the v3 runtime since we'll have written it as a raw string value.

Having `{{ @input.foo }}` for a string field with enum works perfectly fine in the runtime execution. The value is computed before the validation check

The problem occurs in the Page Editor, where it crashes when loaded in the page editor because the select widget can't handle an object

## Proposal

My proposal is to:

1. v3 Page Editor: if the property is a string property with an `enum` section, show the following options: 1) select (produces a string literal), 2) variable, and 3) text template. 
   a. Do not modify the select widget
   b. The Text Widget should be able to load a string literal, but once the user modifies it, it produces the text template expression. (IIRC, this is already the behavior)
2. Upgrade: if the field looks like a var/template, produce a var/template expression. Otherwise produce the literal
   a. The upgrade code doesn't have to look at enum/examples

This is the most robust approach because it also properly handles hand-written YAML where the user didn't provide write a `!nunjucks` before the text.

**Comment by BLoe** [comment]
Support for select-number is being split and moved to a future work item: https://github.com/pixiebrix/pixiebrix-extension/issues/2341

**Comment by BLoe** [comment]
## Implementation Sketch

### Goals
1. Support both the text and select toggle options on the same field
2. Modify the `upgrade.ts` logic to _ignore_ any select fields for conversion to v3 expressions
  * This change is trivial, 1 LOC, the rest of this applies only to Goal#1

### Considerations
* For `1.`, the main issue right now is that text and select both fall under the schema `type` of `"string"`.
Here are the schema types and the input modes they correspond to:
```
export type JSONSchema7TypeName =
    | 'string'
    | 'number'
    | 'integer'
    | 'boolean'
    | 'object'
    | 'array'
    | 'null';

export type FieldInputMode =
  | "string"
  | "var"
  | "number"
  | "boolean"
  | "array"
  | "object"
  | "omit";
```

| JSONSchema7TypeName | FieldInputMode | Widget |
| ------------------------- | ---------------- | ------- |
| `string` | `string` | `TextWidget` |
| `number` | `number` | `NumberWidget` | <-- xor
| `integer` | `number` | `NumberWidget` | <--/
| `boolean` | `boolean` | `BooleanWidget` |
| `object` | `object` | `ObjectWidget` |
| `array` | `array` | `ArrayWidget` |
| `null` | `omit` | `OmitFieldWidget` |

* The function `inferInputMode()` in `fieldInputMode.ts` uses `typeof` to infer the input mode from the current field value
* The toggle options in the field toggle dropdown are keyed based on the `FieldInputMode` they correspond to, and there's always a `1:1` ratio with options and type name, because number/integer options are never shown at the same time (the user is free to enter an integer into a number field if the schema supports both)
  * The toggle option key must be type `string | number`, it can't be an `object`

#### Future
* Don't block #2341 - Don't implement anything that makes it harder to support select-number fields in the future, which would be a field schema with `type: "number"` and with the `enum` field populated with an array of numbers.

### Options
1. Add a new `FieldInputMode` of `select`
  * We now have a new toggle option key to use in the dropdown button for field type
  * `inferInputMode()` will now have to also accept the field schema as an input in order to tell the difference between text template and select option, which means that it's caller, the `useToggleFormField()` hook, will also need to accept the field schema as an input, because the field schema is available at the stack level where the hook is called
2. Re-integrate `(v3) TextWidget` and `SchemaSelectWidget`, don't add a new `FieldInputMode`
  * The work to re-integrate these two components back into one `TextWidget` wouldn't be too bad, just copy-pasting some blocks of code back into `TextWidget`
  * No longer need to modify the `inferInputMode()` function at all
  * Need to serialize and deserialize a toggle option to and from a "key" string using more than just `FieldInputMode`, since both text and select will still be using the input mode `"string"`
  * `getOptionForInputMode()` in `TemplateToggleWidget.tsx` will now need to accept the field schema as an additional input, which is available at both call sites for the function

### Analysis
Option `1.` seems like less work, but it ends up with the awkward situation where the field schema is drilled down through the `useToggleFormField()` hook to use with the `inferInputMode()` function. Option `2.`, though, involves passing the field schema in to the `getOptionForInputMode()` function in two locations, and also using a combination-key of toString() values for the dropdown item keys, which are both slightly awkward, so it's not like option `2.` is perfectly clean either. We separated concerns between `TextWidget` and `SchemaSelectWidget` for code/architecture clarity reasons, and it would be nice not to have to revert that decision.

### Decision
We should do option `1.`, because passing down the parameter isn't that bad. The new `FieldInputMode` adds code clarity, as does keeping `SchemaSelectWidget` separate from `TextWidget`.
