### ISSUE TITLE
Block automatic v2 to v3 upgrade of extensions that are part of a blueprint with multiple extensions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2306]
Discussion here: https://github.com/pixiebrix/pixiebrix-extension/pull/2298#issuecomment-1007003564

**Comment by BLoe** [comment]
Product considerations:

When someone tries to open an extension with runtime api v2, that's also part of a published blueprint _with more than one extension in it_, we don't want to just block everything and scare people away. But, we also can't auto-upgrade the extension and then allow saving the blueprint, because it would then have extensions with inconsistent runtime api versions, which causes other problems. Instead, we'll run the auto-upgrade logic on the extension in the page editor. but modify the save wizard. It will only allow saving the extension as a local extension, not the blueprint.

**Comment by BLoe** [comment]
When the extension is part of a blueprint, but is the _only_ extension in the blueprint, then we should allow updating the blueprint on save, and then update the `apiVersion` field in the blueprint.
