### ISSUE TITLE
contentScript not ready in 4s when opening the Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2366]
Impacts 1.4.12 (and looks like Chrome 97). @fregante, any ideas of potential causes?

![image](https://user-images.githubusercontent.com/1879821/149156382-e5b42624-8b29-4db3-9c21-8f7b6a62479f.png)

**Comment by fregante** [comment]
Likely related to permissions, this is probably not a new bug. Example: 

- https://github.com/pixiebrix/pixiebrix-extension/issues/1759

**Comment by fregante** [comment]
I was able to replicate this:

1. Open editor
2. Reload background page
3. Reload editor

It's probably failing because the injection of the content script on that domain is Chrome’s responsibility:

https://github.com/pixiebrix/pixiebrix-extension/blob/2e44b8dd19fa8d3730c4e5b903b05c20c8f24db7/src/manifest.json#L22-L29

This is fine when you open the page and Chrome injects it, but if you reload the background page, the content script will not be injected again.

Interestingly I wrote a possible solution to this a few years ago, 😅  but I'm not sure how up-to-date it is:

https://github.com/fregante/webext-inject-on-install

**Comment by fregante** [comment]
How much of a problem is this in practice though? Reloading the background page generally breaks a lot of places. What we can do is improve the error messages. In this case the solution should be:

- reload the page (so that Chrome will inject the CS)

The alternative could easily bring back duplicate injections, which we eliminated a long time ago.

Solution demo:

https://user-images.githubusercontent.com/1402241/149179073-3177d7f1-dc7d-4508-ab9b-953b75b852f0.mov

**Comment by twschiller** [comment]
I suspect the issue that Anders is seeing is not caused by a reload of the background page. He would have already been on 1.4.12

If this is an uncommon occurrence, maybe we just clean up the messaging a bit? I left a related comment here: https://github.com/pixiebrix/pixiebrix-extension/pull/2356/files#r783382677

A path forward might be:
- Change the error message to be: "The Page Editor could not establish a connection to the page" (this will also help us track more accurately in error telemetry/Rollbar)

Change the copy for that error screen to just say (without "An error occurred"): "The Page Editor could not establish a connection to a page" with a "Reconnect" button?

Thoughts?

**Comment by fregante** [comment]
If they still see this issue, it'd be great to have exact repro steps so I can look into it again.
