### ISSUE TITLE
Confusing error if condition left blank

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2427]
Steps to reproduce:
1. Add a condition to a brick
2. Erase the text, so the field is a blank "@" toggle

When you run the extension, you'll get an error. In the console there will be an error about "trim"

Questions:
1. We should probably change the condition field to omit if the user clears it out while it's in var mode?
2. Should we address this in the runtime? I.e., treat null var expression value as undefined?

**Comment by BLoe** [comment]
Something is taking the empty string `if.__value__` from the form state and stripping it out so `blockConfig.if === {__type__: "var"}` and nothing else. This breaks because the logic checks to make sure the `if` field is defined, but then unwraps it and doesn't check the value. I think this would probably be fine if it just left it as empty string. Alternatively, there's code somewhere that needs to be checking if `__value__` is undefined and then stripping out the entire `if` object, not just recursively checking fields and stripping them.

**Comment by twschiller** [comment]
[This is the culprit](http://github.com/pixiebrix/pixiebrix-extension/blob/b1585868a3299072258a78eb10ab54752edcfcf2/src/devTools/editor/extensionPoints/base.ts#L347-L347). We had added it when there was no "omit" option for fields (and therefore no way to pass nothing once you touched the field)

I would be in favor or having the var/template fields change to omit on blur if the value is the empty string. I don't know of any bricks where you'd need to pass the empty string through as an argument

I think we want to always keep the `__value__` prop around, otherwise we'll need to add null coalescing code in numerous places (e.g., the YAML serializer). So we should probably also modify removeEmptyValues to ignore expressions

**Comment by twschiller** [comment]
This also comes up with normal fields, see Mike's comment here: https://pixiebrix.slack.com/archives/C02CN01JXAA/p1642648426062400
