### ISSUE TITLE
Move copy/remove brick buttons to node layout header

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2501]
* Create a header on the editor node layout
* Move copy/paste brick buttons to the header
* Make sure we only enable the buttons if a pipeline brick is active/selected, not the foundation node
  * For the foundation node, disable the buttons and add a hover tooltip that says "Can't copy/remove foundation node"

**Comment by fregante** [comment]
Would it make sense to drop/move these the existing Edit/Logs "tabs"?

<img width="211" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/151546622-8d67a4cb-d8cc-46e9-b344-b4d94c02d71d.png">

Adding another bar for "copy/remove/up/down" buttons just below them will likely make it difficult to understand the hierarchy of the UI. I'm not sure where "Logs" could be moved, maybe this? Rough mockup:

<img width="1012" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/151547326-d32fd387-b4bd-4e53-8858-6acc43ef9746.png">

**Comment by twschiller** [comment]
> Adding another bar for "copy/remove/up/down" buttons just below them will likely make it difficult to understand the hierarchy of the UI

The buttons for copy/delete need to be part of the "Extension Overview". I agree that we may want to make the Extension Overview area more explicit. (E.g., currently it's only separated from the brick configuration via padding

The problem with putting them in the tab bar is that bar also has "Save"/"Reset"/"Remove" which apply to the whole extension, and not just the selected brick(s)

One alternative we might consider is adding a menu (either above or below) the selected brick. However, I like the idea of having it above the Extension Overview because that provides an affordance for actions over multiple bricks in the future (e.g., to extract multiple selected bricks into their own component)
