### ISSUE TITLE
Clicking on a quick bar item doesn't trigger it on the first try

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2594]
Steps to Reproduce
- Open the quickbar on a page pixiebrix already has access to
- Click a quick bar item
- It shows an expand/click animation, but doesn't run the brick
- If you click it 1-2 more times then the brick will run

Other Considerations
- If you key down to the item and press enters it runs on the first try

**Comment by fregante** [comment]
I'm not sure I fully understand all the code that Kbar requires. For me the action is being run, but Kbar immediately reappears. Could this somehow be due to "autoshow"? Either way I don't have an answer here.

https://user-images.githubusercontent.com/1402241/152646332-9a50e8bc-d3e2-4307-b449-365e73586a5e.mov

**Comment by twschiller** [comment]
I'm getting erratic behavior. Sometimes the first click will trigger it. Sometimes it won't

The "Enter" handler just simulates a click: https://github.com/timc1/kbar/blob/main/src/KBarResults.tsx#L77

The code for hiding the KBar after the action looks straight-forward: https://github.com/timc1/kbar/blob/main/src/KBarResults.tsx#L114

I adding logging to our autoShow, and that doesn't look like the problem

**Comment by twschiller** [comment]
Likely a problem in our code? https://www.loom.com/share/dafd389814bd4766be0e0637ef933553

I have to look for other ways that the KBar would be getting toggled off without going through that breakpoint
