### ISSUE TITLE
Can't enter keys with periods into Object Entry in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2718]
Steps to Reproduce:
- Use the object properties toggle. E.g., in Mapping brick
- Write a key that contains a period, e.g,. "github.com"
- Click away
- The key becomes corrupted

Underlying cause:
- Formik uses "." to indicate nesting

Discussion/Considerations
- This will also impact the field even if we switch to Redux for the outer part of the extension state
- We still want to allow objects to be passed to bricks (as opposed to an array of key/value entries, which would bypass the issue but be annoying to deal with within bricks)
- The solution might involve representing all objects in Formik as key/value but remapping to the brick state?

Related Issues:
- https://github.com/pixiebrix/pixiebrix-extension/issues/1392

**Comment by fregante** [comment]
I suppose this is a duplicate:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1749

**Comment by BLoe** [comment]
I'm not so sure this is a limitation with Formik, but more with how we've designed our field name handling in `SchemaField` and throughout the extension. We've always taken the approach of just smushing the names together into one `fieldName` or `name` type of prop.

After some experimenting with `ObjectWidget` I think we can handle this without changing the formik structure, but it requires, for example, splitting `SchemaFieldProps.name` into a parent "path" prop and a fieldName prop. This obviously impacts many different components and is a large, cross-cutting code change due to the number of files and components it would touch, but the changes seem somewhat straightforward to me. Would just be a matter of basically QA-ing the entire extension deeply anywhere we have fields I think.

**Comment by twschiller** [comment]
> I'm not so sure this is a limitation with Formik

Formik by default uses lodash style property paths in the name. I has a "getIn" utility method is uses. So useField("a.b") is interpreted as referencing the nested b field on a. To avoid this behavior, you can explicitly opt out: https://formik.org/docs/guides/arrays#avoid-nesting. I'm not sure if this works to combine names, e.g., `property.['owner.fullname']`. 

For this issue, I think what we need to do is modify ObjectWidget to surround the property with `[' ']`: See here: http://github.com/pixiebrix/pixiebrix-extension/blob/eef0e0f95a70dc9897951d3040e0874e35aae52a/src/components/fields/schemaFields/widgets/ObjectWidget.tsx#L266-L266

To fix the problem generally I think we just need to be more careful when joining dynamic path parts together. I think there's only a few places:

![image](https://user-images.githubusercontent.com/1879821/154822441-c96ee5fa-5b19-46a7-b0eb-878274d501b0.png)
