### ISSUE TITLE
Spike: alternatives for splitting presentational/connected part of components

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2755]
Goals
- Provide concrete options for the team to decide how we want to split presentation and connected components

Choices for connecting to the store:
- Hooks: useSelector/useDispatch
- connect, with mapStateToProps, and mapDispatchToProps

Organization Choices:
- Separate files, e.g., `Component.tsx` and `Component.connected.tsx`
- Default export the connected version of the component

```
export Component: React.FC<Props> = () => ...
export default connect(mapStateToProps, mapDispatchToProps)(Component)
```

**Comment by BALEHOK** [comment]
**Current state.**
We use hooks to connect components and **custom hooks** to the Redux store.
Redux hooks are convenient from the feature implementation perspective. When it comes to unit tests and storybook it becomes challenging to test or showcase such a component.

**Options**
1. Keep using Redux hooks. Will have to init store in tests and/or storybook (see current implementation).
2. Split component and connection to Redux. Works well for components, the problem is the custom hooks that use Redux hooks.
Let's take a look at [LogCart](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/logViewer/LogCard.tsx#L41:L46) and its [tests](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/logViewer/LogCard.test.tsx#L49).
We can remove `useSelector` and `dispatch` from the component however, the hook that LogCart uses still depends on them, need to refactor the hook as well.
Updated [LogCard](https://github.com/pixiebrix/pixiebrix-extension/blob/d593732238a1c731b8aedf40b1bf8227c4b69373/src/components/logViewer/LogCard.tsx#L41) and [its tests](https://github.com/pixiebrix/pixiebrix-extension/blob/d593732238a1c731b8aedf40b1bf8227c4b69373/src/components/logViewer/LogCard.test.tsx#L31)

**Comment by BALEHOK** [comment]
Considering the RTKQ boilerplate personally I'd keep using Redux hooks.

@twschiller @BLoe @mnholtz question, comments, thoughts?

**Comment by twschiller** [comment]
Thanks for looking into this. A couple interesting things:
- The Redux team is recommending to use hooks over connect. And, also they're strongly recommending connecting more components to the store (instead of splitting into presentational vs. connected): https://redux.js.org/style-guide/style-guide#connect-more-components-to-read-data-from-the-store
- The Redux testing information has links talking about how redux testing strategies have evolved as React has moved toward hooks: https://redux.js.org/usage/writing-tests. For example, one approach is to re-define a "render" method to use in tests

**Comment by BALEHOK** [comment]
Re problems:
1. We've got [formHelpers](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/tests/formHelpers.tsx) that helps to test form components. We can add utils that will help to wrap a component under test in a Redux Store. Redux team recommends writing integration tests over isolated component tests, that's cool and is a bit easier in terms of store initialization, but some of our components are shared between 2 apps. I suggest we define a store for the concrete test ([see LogCard.test](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/logViewer/LogCard.test.tsx)).

2. `useAsyncState` by itself is not a blocker. What makes it difficult to test is what's happening inside the callback. Maybe we should mock (globally?) the services that we often access within `useAsyncState` (like `blockRegistry`)? If a callback in the `useAsyncState` can run under test, let it run, a step towards integration testing.

3. Definitely we should work on standardization of how we handle the state of an async operation.

Looks to me that we can keep using the Redux hooks, create 3 actionable items, and improve our tests?

**Comment by BLoe** [comment]
If the Redux team is recommending hooks, then I think we should stick with that approach.

>For example, rather than just connecting a <UserList> component and reading the entire array of users, have <UserList> retrieve a list of all user IDs, render list items as <UserListItem userId={userId}>, and have <UserListItem> be connected and extract its own user entry from the store.

This example seems to show that they want people to go as granular as possible with `useSelector()` and connecting to the store. Using hooks also makes it a lot easier to refactor things to be more granular later on, compared to splitting apart a connected component.

As far as testing goes, I like [their suggestions](https://redux.js.org/usage/writing-tests#components) about writing more integration tests where we set up a real store and test integrated app behavior. Maybe we can start with Aleksandr's method of using `configureStore()` in tests, and see what common patterns emerge that we can extract out to make the test code even simpler at some point?

**Comment by BLoe** [comment]
@grahamlangford I don't think this ticket is very relevant anymore; afaict, we settled on sticking with hooks as opposed to connected components and there's not much else to do here 🤷
