### ISSUE TITLE
Menu Item extension point double reporting to Rollbar (and one is at wrong level)

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2900]
Steps to Reproduce
- Add a BusinessError to a menu item extension
- Run the extension

Actual Behavior
- Reported twice to Rollbar: a) once as debug level with the BusinessError, and b) once at error level with message "Error running action"
- Notify the user with 

Expected Behavior
- Reported once to rollbar at debug level with the BusinessError

Implementation Sketch
- Suppress notifyResult from reporting error here by passing includeErrorDetails=false: http://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/menuItemExtension.ts#L564-L564
- Is this also going to report the error multiple times?: http://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/menuItemExtension.ts#L737-L737

What other locations are impacted?

**Comment by fregante** [comment]
> * Suppress notifyResult from reporting error here by passing includeErrorDetails=false

- `reportError: false` stops the automatic reporting
- `includeErrorDetails` only appends `error.message` to the notification itself, it's unrelated to reporting

**Comment by fregante** [comment]
> * Suppress notifyResult from reporting error here by passing includeErrorDetails=false

- `reportError: false` stops the automatic reporting
- `includeErrorDetails` only appends `error.message` to the notification itself, it's unrelated to reporting

**Comment by fregante** [comment]
I've been reviewing the runner and I found a few places where errors are caught, logged and thrown again, or returned, or swallowed even though the outside caller has a try/catch. This will inevitably cause duplicate reports. 


Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1562
- https://github.com/pixiebrix/pixiebrix-extension/issues/580


I don't have enough context to refactor this piece of code right now, but currently `TriggerExtensionPoint.notifyErrors` is just not called anywhere, it seems, because in `runExtension` we catch and log it…

https://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/triggerExtension.ts#L275-L277

… and then we try to catch it (but it never reaches this point), report it, and return it…

https://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/triggerExtension.ts#L316-L318

… for yet another handler to catch it downstream:

https://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/triggerExtension.ts#L327-L333

**Comment by twschiller** [comment]
I added comments to the PR to explain the trigger code.

The distinction is between two concerns: 1) reporting each error for telemetry, 2) notifying the end-user something failed. The downstream handler has a different purpose - it's grouping so the user isn't inundated with messages
