### ISSUE TITLE
Add telemetry to determine Page Editor success rate

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2924]
Context
- As a product manager, I want to measure what percentage of the time someone using the page editor are successful
- Currently we track PageEditorStart (add new) and PageEditorCreate (save)
- We don't have anyway to know what % of the time a user is successful in creating a new extension. (Users may save an extension even if it's not working, just so they don't lose their work)

Implementation Sketch
- Generate a editing "sessionId" on mount
- Add PageEditorInit event on mount with the sessionId
- Add the following events: PageEditorOpen, PageEditorReset, PageEditorRemove
- For these and PageEditorStart, PageEditorCreate, [BrickAdd](http://github.com/pixiebrix/pixiebrix-extension/blob/d6e36801d248c31f83230b351c46a1618692ba0c/src/pageEditor/tabs/editTab/useBlockPipelineActions.ts#L81-L81) add the following data:
   - sessionId
   - extensionId 

Future improvement:
- Track the extension type (e.g., quickbar, etc.)

**Comment by orliesaurus** [comment]
Things that come to mind are output errors:

- Errors: When creating an extension and saving it, if errors are produced followed by no additional edits. You can consider that a "dead" extension. 
For example:
Let's assume I am trying to get all the HTML <p> elements page in a blog so that I can calculate the average length of a sentence.
- I add a trigger brick
- I add the JQuery brick
- I configure the brick(s)
- I save the extension
- I try to run it 
- PixieBrix spits out an error that there are multiple elements in the page with the same selector
- I might try to change the configuration a little bit
- The error keeps appearing because this feature isn't currently supported
- I give up on this use-case

Thus in this example, the extension will output an error every single run, we can consider this use-case "dead".


On the other hand if my use-case is to create a button that opens a specified link in a new tab.
- I go through setup, add 2 bricks etc etc
The extension will not produce an error at the end and will actually open the new tab.
Now as a user I will be using this extension numerous times throughout my day to day and no errors are produced.
This is a successful usage of the extension

If every extension has a unique identifier, we can track how many extensions with a unique identifier have produced errors and then were never run again vs extensions that are unique and are completing their runs every time they're being triggered
