### ISSUE TITLE
Clear token button broken on settings page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3004]
Steps to reproduce
- In the extension options go to the Settings screen
- Hit "Clear Token"

Expected Behavior
- Token is cleared from local storage and page reloads
- Extension shows the 2-step onboarding screen

Actual behavior
- Page reloads
- User still shows as logged in
- When you visit the Admin Console, it shows the "succesfully linked extension" message indicating that the auth token might be getting cleared, but the user profile state isn't?

**Comment by BALEHOK** [comment]
What happens is as follows:
1. the Options page clears the token, but can’t clear the cookies set for `https://app.pixiebrix.com/` domain
2. when the page reloads, the token is undefined (hence no 401 as we discussed recently) and `session` cookie is still there (set by admin app), so the user actually gets the data from the API
3. if I clear the token from Options and Log out from Admin, I can see the 2-step onboarding screen

Following are the examples of requests, the `Authorization` header and `cookie` is what matters. Also note that the response status is 200 in all the cases.

The `/blocks` request when I’m fully logged in
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/3116723/159916308-c362dbf4-c88c-480d-92f2-e3e0b8051db3.png">

`/blocks` request if I clear the token
<img width="1382" alt="image (1)" src="https://user-images.githubusercontent.com/3116723/159916464-b6aa6a10-a6c8-430c-b5c0-bed82a7a6796.png">

`/blocks` request if I log out and clear the token (the Setup screen shown in this case, because the `me` is empty and `me.isLoggedIn` is false)
<img width="1383" alt="image (2)" src="https://user-images.githubusercontent.com/3116723/159916484-9d289450-1d89-49a2-a1f9-72b6c9e25c30.png">

**Comment by fregante** [comment]
Slightly related, but I'm not sure if it's still up to date:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2710

**Comment by twschiller** [comment]
> when the page reloads, the token is undefined (hence no 401 as we discussed recently) and session cookie is still there (set by admin app), so the user actually gets the data from the API

Interesting, I didn't realize the cookies were being sent along. (Thought it would be treated as cross-origin request).

> Slightly related, but I'm not sure if it's still up to date

Definitely seems related

The intended behavior of the "Clear Token" endpoint is to unlink the extension. The state where there's a profile loaded but no token is invalid

Now that I think of it, we were actually seeing this behavior with the Trello integration. PixieBrix was passing along the session with Trello requests, requests were working off the session and not the token (hiding the fact that the token was invalid)

In the extension, I think the correct behavior is to do API calls without cookies. We always want to be using the token, and for 3rd party services, the integration settings
