### ISSUE TITLE
Report CSP errors?

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3013]
Interesting global event, maybe we can handle it similarly to [uncaught errors](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/reportUncaughtErrors.ts): 

- https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent

@twschiller This might be a partial answer to “how do we know why a request failed”?

**Comment by twschiller** [comment]
Worth a shot, especially since we've been having network errors.

If we add this, we should only add on our extension pages. Would be way too noisy in the content script (b/c I think we'd pick up CSP errors from the host page)

Potentially could also combine with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri, but that wouldn't give user-level information

**Comment by twschiller** [comment]
Potentially related: https://github.com/w3c/webextensions/issues/197
