### ISSUE TITLE
High rate of un-enriched network errors 

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3020]
Investigation:
- Related to how axios-fetch-adapter captures/rethrows errors? https://github.com/vespaiach/axios-fetch-adapter/blob/main/src/getResponse.js

Example occurrences:
- https://rollbar.com/pixiebrix/pixiebrix/items/2546/occurrences/220906627426/

**Comment by fregante** [comment]
This is already taken care by https://github.com/pixiebrix/pixiebrix-extension/pull/3014

It's waiting for your review

**Comment by twschiller** [comment]
> This is already taken care by https://github.com/pixiebrix/pixiebrix-extension/pull/3014

Could you confirm that it works (and that the data flows correctly to Rollbar). I confirmed that you have the necessary permissions in Rollbar to confirm

Also, as part of this issue I want to double-check that the error handling in the axios-fetch-adapter library is correct. Were you able to confirm as part of the PR?

**Comment by fregante** [comment]
> * Related to how axios-fetch-adapter captures/rethrows errors?

That doesn't seem to match the timeline since the adapter was added in December while these error spiked in early March and it hasn't been updated since:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2108

<img width="325" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/159970589-e6dfcbf5-8264-49a6-8b99-af8ba005146e.png">
 

> Could you confirm that it works

I have not tested the PR yet because it's incomplete: I wanted to make sure it was a sensible idea before I spent any more time on it. 

> and that the data flows correctly to Rollbar

Do I have to do anything specific to send errors to Rollbar from my local version? Or do I use `reportError` as usual and wait for it to appear in Rollbar?

> Also, as part of this issue I want to double-check that the error handling in the axios-fetch-adapter library is correct. Were you able to confirm as part of the PR?

I wonder if `fetch` leaks those Network errors (they look like what appears in the console) but then again the timeline doesn't match. I will try with and without the new adapter.

**Comment by twschiller** [comment]
> That doesn't seem to match the timeline since the adapter was added in December (and it hasn't been updated since) while these error spiked in early March

I suspect the increase is related to: 1) increase in enterprise users, 2) one of our enterprise clients moving back into the office where one of their VPNs/firewalls may be blocking some requests

I don't think the adapter is causing the requests to fail. I think the problem is that the adapter might not be forwarding the response:

Here is the createError call: https://github.com/vespaiach/axios-fetch-adapter/blob/main/index.js#L51

![image](https://user-images.githubusercontent.com/1879821/159996902-6205b016-9cde-4230-899f-332a7b5dc715.png)
