### ISSUE TITLE
Being offline is reported as "unlinked" and it kicks the user to the setup page

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3036]
The extension doesn't really work when offline, but it probably shouldn't suggest that the extension hasn't been linked. 

"Being offline" could also happen when the connection is flaky and one request fails.

Note that going online and refreshing the page will fix the error, without further action, so the link is not actually lost.

This is what appears when going offline:

## Page editor

<img width="615" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/160271102-f50a5107-e71f-4b91-ad5a-966bd8663e08.png">

## Options

<img width="1221" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/160271100-5fd6ecbb-6216-4560-8cd2-169d4afb55a5.png">

**Comment by twschiller** [comment]
The "linked" check needs to be based on the authentication token. See PR: https://github.com/pixiebrix/pixiebrix-extension/pull/3053

The RequireAuth gate should probably show an "offline" page if the "/api/me" query fails due to a NetworkError (there's no response) 

cc @BALEHOK

**Comment by twschiller** [comment]
Implementation Sketch:
- In [RequireAuth](http://github.com/pixiebrix/pixiebrix-extension/blob/9c31084c12a86ed5a3976d19f1cbab467b0254c7/src/auth/RequireAuth.tsx#L63-L63), if useGetMeQuery fails without a response show a "Cannot connect to PixieBrix" page with a button to reload the page. (We might be able throw a "Cannot connect to PixieBrix" error since our default page shows a reload button?) 
- If the useGetMeQuery failed without a response, do not clear user data by passing blank to [updateUserData](http://github.com/pixiebrix/pixiebrix-extension/blob/9c31084c12a86ed5a3976d19f1cbab467b0254c7/src/auth/RequireAuth.tsx#L77-L77)
