### ISSUE TITLE
Figure out managed storage on Mac for local development

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3133]
Context
- We added managed storage to pre-configure settings for PixieBrix
- I tried setting the managed storage state on Chrome on Mac, but can't get our extension to see it

Steps to Reproduce
- Download https://www.fatcatsoftware.com/plisteditpro/
- Navigate to ~/Library/Preferences
- Create a com.google.Chrome.extensions.mpjjildhmpddojocokjkgmlkkkfjnepo.plist file. I think this is the right way to do it? I also have com.google.Chrome.app.mpjjildhmpddojocokjkgmlkkkfjnepo. Not sure which one actually caused the data to load
- Run `defaults read com.google.Chrome.extensions.mpjjildhmpddojocokjkgmlkkkfjnepo.plist`. Running it without the .plist also works. I'm not sure what's the right way to do it
- Visit `chrome://policy/`, and verify the properties are set. You might have to restart Chrome for the managed state to flow through? I had issues getting it to reflect instantly. But that might have also been I'm not 100% sure how to correctly se the plist for the extension storage
- Add logging to deployments.ts and see that properties aren't found in managed storage when the background page reads it

Example Policy: the values don't really matter yet. The deployments.ts module has logic based on whether managedOrganizationId is set at all though

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>managedOrganizationId</key>
	<string>0557cdab-7246-4a73-a644-12a2249f02b9</string>
	<key>partnerId</key>
	<string>todd</string>
</dict>
</plist>
```

Discussion
- Does managed storage work with unpacked extensions?
- If not, we probably want to add logging to help debug the CWS version if needed

Related
- Potentially related discussion of bug in Chrome on loading managed state: https://github.com/EFForg/privacybadger/issues/2832
- https://support.google.com/chrome/a/answer/9020077?hl=en: these instructions I think are super out of date/wrong (for old version of Mac, and reference a Python 2 utility from 6 years ago)
- https://www.chromium.org/administrators/configuring-policy-for-extensions/
- https://superuser.com/questions/1334850/chrome-not-updating-policy-list-from-library-preferences-com-google-chrome-plis
- https://github.com/w3c/webextensions/issues/174

**Comment by twschiller** [comment]
@fregante I think you're on a Mac, correct?

**Comment by twschiller** [comment]
@fregante what's interesting is that when I do it on Windows it works. The difference I see at chrome://policy is the Level is Recommended on Mac, but Mandatory on Windows:

![image](https://user-images.githubusercontent.com/1879821/164122231-e4b950c5-7b4d-42f8-92e5-1144cf9bd711.png)

**Comment by fregante** [comment]
Findings:

- [plisteditpro](https://www.fatcatsoftware.com/plisteditpro/) is not required, we can use raw XML
- To load/update the policy:
	1. Run `defaults read com.google.Chrome.extensions.mpjjildhmpddojocokjkgmlkkkfjnepo.plist`
	2. Restart chrome
- "Reload policies" does nothing
- Invalid keys do not appear in `chrome://policy`, this means Chrome is correctly matching the keys to the manifest’s schema
- Firefox uses a different policy format and location, we could potentially use that to debug managed storage if Chrome is unwilling https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#managed_storage_manifests
- Even if the policy is read correctly by Chrome and I'm using [the same API as Google’s samples do](https://github.com/GoogleChrome/chrome-extensions-samples/blob/e716678b67fd30a5876a552b9665e9f847d6d84b/mv2-archive/extensions/managed_bookmarks/background.js#L302), `chrome.storage.managed.get(console.log)` still returns nothing in `background.js`
- [Their docs](https://www.chromium.org/administrators/configuring-policy-for-extensions/) _"assume that the sample extension has been loaded as an unpacked extension,"_ so presumably this should work.


## Demo `chrome://policy`

<img width="1111" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/167244883-6556e1e8-029e-41d6-9901-1ea21b1203a0.png">


## Next

I will try working backwards from their sample extension because the suggested commands are different than what you suggested here, but they don't appear to work at all if I adapt our extension to them 😬 

- https://github.com/GoogleChrome/chrome-extensions-samples/blob/e716678b67fd30a5876a552b9665e9f847d6d84b/mv2-archive/extensions/managed_bookmarks/schema.json
- https://www.chromium.org/administrators/configuring-policy-for-extensions/
- `dscl -u YOURUSERNAME /Local/Default -mcximport /Computers/localhost A-LOCAL-CONFIG.plist`
- There's a `Directory Utility.app` is appears to be a (partial) GUI to `dscl`

**Comment by twschiller** [comment]
You could try reaching out to the Privacy Badger team. They have managed storage working on Linux/Windows at least

We could be hitting something related to this? https://github.com/EFForg/privacybadger/pull/2834

Also probably makes sense to open a bug ticket with Chrome

Any next steps I could potentially help out with?
