### ISSUE TITLE
Refactor Page Editor flows from top-level state

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3264]
Currently we are keeping track of the saving wizard in the flat top-level state of the editorSlice. 

- transitionSaveAsNewToCreateRecipeModal/transitionAddToCreateRecipeModal
- Refactor isModalVisibleState

**Comment by BLoe** [comment]
@grahamlangford I think the only remaining piece of this that is applicable is the [`keepLocalCopyOnCreateRecipe`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/pageEditorTypes.ts#L175) flag in the editor state. The way we handle Modals was changed quite a bit since this ticket was written.
