### ISSUE TITLE
Wrong logo in browser toolbar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3437]
Context
- For small logos (favicon, browser toolbar), we use a 3 box logo without anything in the boxes
- I think in the Theme PR we accidentally switched over to the detailed logo? I see this in 1.6.3-alpha.3

**Comment by fregante** [comment]
Likely this line:

https://github.com/pixiebrix/pixiebrix-extension/blob/e4d3bb00a3e3ca94be23abebdde44d0a697a9c17/src/background/partnerTheme.ts#L24

Instead of manually picking a default URL, I think we can pass the whole default dictionary from the manifest, like I'm doing in `activateBrowserActionIcon`, or we just call that:

```js
if (default) {
	activateBrowserActionIcon()
} else {
  (chrome.browserAction ?? chrome.action).setIcon({ path: logo.small });
}
```
