### ISSUE TITLE
Set wasm-unsafe-eval in CSP?

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3447]
Context
- https://github.com/w3c/webextensions/issues/98#issuecomment-1106702230
- Our jq brick uses a WASM module? Or is Ecmascripten not impacted? https://github.com/fiatjaf/jq-web
- Do we need to set a wasm related key in our CSP? Do we have a risk of breaking in future versions of Chrome?

@fregante could you help look into this?

**Comment by fregante** [comment]
emscripten is that tool that compiles into WebAssembly (AKA Wasm), so yes in theory it does affect us.

From what I understand, they're adding a wasm-specific key `unsafe-eval` key so that you can enable `unsafe-eval` for Wasm. The motivation paragraph here should be clear on this:

- https://chromestatus.com/feature/5499765773041664

Since we already have an all-encompassing `unsafe-eval`, we don't need to specify the `wasm-unsafe-eval` subset.
