### ISSUE TITLE
Selector inference for button location including excluded attributes

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3452]
Steps to reproduce
- Reproduced on 1.6.3-beta.1
- Add a button in the quick start: https://docs.pixiebrix.com/build-your-first-extension and save
- Perform the quick start again

The location is suggesting selectors it shouldn't:
- `[id="emberN"]` selectors
- `[data-pb-extension-point]` selectors

![image](https://user-images.githubusercontent.com/1879821/169720286-b2625d0d-a4ae-4687-9350-408b76b9914e.png)

**Comment by fregante** [comment]
I saw two issues:

- the library is generating `[data-pb-extension-point]` but that does not match our blocked pattern `[data-pb-extension-point='*']` because the pattern simply replaces `*` with `.+` and treats it as a regex, it's not smartly detecting it as a attribute selector
- the `[id=*]` selector is bug I caused here:

	https://github.com/pixiebrix/pixiebrix-extension/blob/8ef695266a7be3d3b3472b2fd5e5b89813f732ef/src/contentScript/nativeEditor/selectorInference.ts#L397

	This line is simply skipping the `#id` optimization rather than excluding the selector.


Will submit a PR
