### ISSUE TITLE
Incorrect font color on disabled buttons

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3537]
- The text color on disabled buttons is incorrect
- The bug was likely was introduced in one of the theming PRs

Let's add button swatch to StoryBook, with:
- Enabled
- Disable
- Each color variant

This screenshot is from the members table in the app:
![image](https://user-images.githubusercontent.com/1879821/171076806-61feb8f2-dd6a-48e5-aca6-a210175cf71d.png)

![image](https://user-images.githubusercontent.com/1879821/171077042-8b669694-68b1-48e4-9c84-4d99b76304a6.png)

@mnholtz could you add any context here? Links to code to look at?

**Comment by mnholtz** [comment]
I think this has something to do with my attempt to implement an equivalent to bootstraps `color-yiq` function, but css-variable compatible for my theming work. This function I wrote is located here: https://github.com/pixiebrix/pixiebrix-extension/blob/e6f5bdc4cfb97215aea25a25e087af5b781e182e/src/vendors/theme/assets/styles/_functions.scss#L11-L13

It might be that we just have to get rid of this function and just make all button text white for now. Implementing this function is challenging with css variables because it requires us defining our theme colors in rgba in addition to hsl.
