### ISSUE TITLE
Add custom lint warnings for direct usage of Formik/Bootstrap <Form/>

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3539]
Our [Form](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/form/Form.tsx) component abstracts away the `<Formik/>` wrapper and `<Form/>` component nesting, and wiring up the handlers and stuff to the form.

We should prefer to use this component when working with Formik/forms in our codebase, so let's add a lint warning for any direct usages of `<Formik/>`, or either Bootstrap or Formik's `<Form/>`.

**Comment by fregante** [comment]
I want to take this, but there are actually quite a few imports (40+). Are they all wrong?

Bootstrap: https://github.com/search?q=repo%3Apixiebrix%2Fpixiebrix-extension+%2Fform.%2Breact-bootstrap%2F&type=code

Formik (some false positives in my search): https://github.com/search?q=repo%3Apixiebrix%2Fpixiebrix-extension+%2Fimport.%2B%28%21%3Ftype+%29%5Cbform.%2Bformik%2F&type=code


### Sample config

To be added to https://github.com/pixiebrix/eslint-config-pixiebrix/blob/81e6a3e51e7b452401f2711bfe89d0690e1e2627/index.js#L52

```js
{
	group: ["formik"],
	importNames: ["Form", "Formik"],
	message: "Import @/components/form/Form instead",
},
{
	group: ["react-bootstrap"],
	importNames: ["Form"],
	message: "Import @/components/form/Form instead",
},
```

**Comment by BLoe** [comment]
Yeah, we either need to fix all the "wrong" usages, and as you noted there are quite a few. Or, we add the lint rule as a warning and we have to live with it for now and fix things incrementally and stop the "wrong" usage going forward. I'm not sure what the best answer to that is right now.

**Comment by twschiller** [comment]
I vote we add the rules as a warning and keep an eye on it going forward. If we feel that this this is the most important tech debt, then we can prioritize as part of in 30% time

**Comment by BLoe** [comment]
Definitely agree that fixing all the wrong usages is not a high priority right now.

**Comment by fregante** [comment]
Rule extended 👆 

---

There are two issues with "warn"

- using "warn" lets us freely ignore rules, even breaking it further instead of having gradual improvement
- this rule actually includes other blocked imports, which are 100% fixed now

If we were to set this to "warn" there's no guarantee that we'd make any progress and there's a chance that we'll lose some.

Case in point:

- I added more rules in [#4728](https://github.com/pixiebrix/pixiebrix-extension/pull/4728) and turned the existing rule into a warning under the same circumstances

We had 58 warnings after that PR was merged and today we have 66. And that was just 1 month ago!

If we want to progress we need to set errors and add explicit `eslint-disable-next-line some-rule -- TODO: Fix` to each one via https://github.com/mizdra/eslint-interactive
