### ISSUE TITLE
Copy/Paste-brick does not restrict where a brick of any type can be pasted

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3730]
We restrict what can be added to a brick pipeline or sub-pipeline through restricting the add brick modal on which brick options it displays to the user to add. The problem is that there is no such restriction on our "paste" functionality, so you can still copy a brick and paste it into an "invalid" location, where you wouldn't have been able to add the brick otherwise.

**Comment by twschiller** [comment]
@BLoe this also is an issue with move up/down. Here's the link to our Slack DM's for posterity: https://pixiebrix.slack.com/archives/D029R8902JF/p1655325573193489

**Comment by twschiller** [comment]
@BALEHOK @BLoe We don't want to prevent the user from moving/pasting bricks. 

Our general philosophy should be that the user should be able to move the extension configuration through intermediate invalid states. Otherwise, the use has to contrive a sequence of steps/modifications where the extension is in a valid state in each

Instead, what we want to do is:
1. Show a warning on the brick configuration if it's in an invalid location
2. Mark on the extension overview if a brick has a warning
