### ISSUE TITLE
Validate syntax of match pattern fields in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3759]
Context
- Match patterns have special restrictions, e.g., need a schema, limitations on where the glob can appear
- If the user writes something, they get no direct feedback that something is wrong. They'll just get some unexpected behavior of where their extension will show up
- Additionally, if the user writes something invalid (e.g., example.com) our permissions check code will fail silently
- https://developer.chrome.com/docs/extensions/mv3/match_patterns/

Implementation Sketch:
- Add Formik validation: URL Pattern Widget

@BALEHOK @BLoe: what would be involved in adding this kind of field validation in the Page Editor? (From a TemplateField and Formik perspective)

**Comment by BLoe** [comment]
I think this would be a good opportunity to refactor-out `ElementWizard` and move the `EditorPane` over in line with `RecipePane`, using the `EditorTabLayout` UI component, and using our `Form` component with a `yup` schema. `yup` can handle any arbitrary validations we want to add, including async validation that could even do network fetches before returning. [This is done through the `test` method.](https://stackoverflow.com/questions/55811114/async-validation-with-formik-yup-and-react). We could set up an async validator that kicks off a new validation on every change, and cancels any in-progress validation. If we can move _all_ of our field validation into an async validation pipeline, we should probably be able to re-enable validate-on-change instead of falling back to validate-on-blur also, without impact to the UI because it's async and not blocking on each key-press. Obviously some of this is theoretical at the moment 🤷  but it's what jumps to mind for me for solving this.

**Comment by twschiller** [comment]
> I think this would be a good opportunity to refactor-out ElementWizard and move the EditorPane over in line with RecipePane, using the EditorTabLayout UI component, and using our Form component with a yup schema.

The limitation of the approach is you'd only see errors for the node you have open. 

We'll need to move toward a world where:
1. The user sees the feedback on the node they're editing, both from the statically known issues and errors from the last run (e.g., dynamic input validation)
2. In the node overview we mark which nodes have feedback
3. Potentially, introduce a pane (e.g., next to logs pane) with all the issues/suggestions

So potentially this is: 
1. Yup tied directly to the Formik pane
2. Yup run over the global state of the extension
3. Yup run over the global state of the blueprint (e.g., if something reads from page state a variable that isn't set anywhere in the blueprint page state)

As I write this, it seems to me instead of using yup for this, that vs. our own function that takes the blueprint/extensions and returns messages/items tied to block instances. (And perhaps uses yup under the hood for some of the checks)

**Comment by fregante** [comment]
`webext-patterns` exports a regex for that: https://github.com/fregante/webext-patterns/blob/c8b54af5008e635b63853290e5fdc2573449af1f/index.ts#L2

But also this produces better errors, as seen in the following screenshot: 
```js
async function assertValidPattern(pattern) {
	await browser.permissions.contains({origins: [pattern]})
}
```

> * our permissions check code will fail silently

It shouldn't fail silently. The extension APIs complain if the pattern is invalid:

<img width="623" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/174473895-9f464f4f-2329-4058-aa56-a696ef98a166.png">

**Comment by twschiller** [comment]
Thanks for the info!

> It shouldn't fail silently. The extension APIs complain if the pattern is invalid

It's our code that's silencing the errors/ignoring them. For example: https://github.com/pixiebrix/pixiebrix-extension/blob/d9358bf57bf94f2aefbf4d726113f3a605034832/src/pageEditor/toolbar/PermissionsToolbar.tsx#L84-L84
