### ISSUE TITLE
Add additional elements to document builder

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3760]
- [x] Markdown: or we can just have our existing text element support markdown?
- [ ] Links: necessary if we have the existing text element support markdown?
- [ ] Tabs (and support mount on entry)
- [ ] Accordion (and support mount on entry)

cc @orliesaurus. Any other feedback here?

**Comment by twschiller** [comment]
Thanks @orliesaurus. For Pagination, do you see that working in conjunction with our table? Or with our List element?

For tooltips, were there particular elements you wanted to attach them to? E.g., table headers? Buttons?

**Comment by orliesaurus** [comment]
Yeah a table works: some sort of filter that allows you to return n results from a returned dataset (like an API call) of many more results and divide them in smaller chunks so that the user can easily navigate them

Tooltips that you can add as an anchor to a heading or a section of a sidebar to explain non-intrusively what's going on with the sidebar

**Comment by orliesaurus** [comment]
Another cool one would be checkmarks todo lists that you can link to the page state perhaps :)
like this:
- [ ] A clickable list

**Comment by twschiller** [comment]
> Another cool one would be checkmarks todo lists that you can link to the page state perhaps :)

You can currently do this with the Custom Form renderer. Does that meet your use case for now?

**Comment by orliesaurus** [comment]
Yeah thank you!

**Comment by twschiller** [comment]
Closing this issue. Will re-open new tickets as necessary from product management
