### ISSUE TITLE
No handler for SIDEBAR_SHOW_FORM error when using Form Builder with location modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3833]
Context
---
- See ticket: https://pixiebrix.zendesk.com/agent/tickets/117
- There appears to be a race condition in the modal location if the sidebar is not already open

Steps to Reproduce
---
- Add a trigger that uses the form builder
- Set the form location from "modal" to "sidebar"
- Run the trigger when the sidebar is not already open

Workaround
---
- Workaround, before showing the form use 1) show sidebar, and 2) wait 100ms

**Comment by fregante** [comment]
I saw this once but I can't replicate it anymore, even when the content script isn't pre-loaded. Do you have any advice on how to make the loading slower?

https://user-images.githubusercontent.com/1402241/179914616-e4835f73-cf96-4f81-9648-3f69a19a6197.mov



https://user-images.githubusercontent.com/1402241/179914582-2968b114-0998-40d6-8eae-5531a15672df.mov

We do call `ensureSidebar` before attempting to message it, but it resolves immediately after the DOM is attached rather than when the sidebar is ready. I'll work on that

https://github.com/pixiebrix/pixiebrix-extension/blob/ccd5ac79c1194c2570665cba9404225123b526b7/src/blocks/transformers/ephemeralForm/formTransformer.ts#L132-L138

**Comment by fregante** [comment]
Can you add me to zen desk? There are 3 separate errors with "no handler for", depending on where they happen. Nothing seems likely though. The only way I see it is when I reload the extension and then trigger context menu.

**Comment by twschiller** [comment]
> Can you add me to zen desk?

I just checked the ticket and there's no additional information in the ticket related to this GitHub issue. 

Looking in Rollbar for the impacted user. I am seeing a lot of the following error occurrences now: 

![image](https://user-images.githubusercontent.com/1879821/180343374-e56aeea8-1f43-4952-a6fb-c327d53aab22.png)

For example: https://rollbar.com/pixiebrix/pixiebrix/items/5090/occurrences/254139350450/

That would be coming from here: https://github.com/pixiebrix/pixiebrix-extension/blob/8d1a3e116b55099628ee1056ff213d14f2d86d10/src/contentScript/sidebarController.tsx#L161-L161

The customer hasn't reported this as being a problem yet...

Here's an example occurrence of the original No handler for SIDEBAR_SHOW_FORM error: https://rollbar.com/pixiebrix/pixiebrix/items/4876/occurrences/254116854219/

Let me know if you have problems accessing the Rollbar occurrences

**Comment by fregante** [comment]
Is this a user-reported error? Are we sure it doesn’t just happen when the extension is reloaded?

**Comment by twschiller** [comment]
> Is this a user-reported error? Are we sure it doesn’t just happen when the extension is reloaded?

Yes, it's user reported. I also saw it during office hours with that user and helped with the workaround (Show Sidebar + Wait). It might be a performance-related race condition -- the computer was relatively resource constrained
