### ISSUE TITLE
Bump Font Awesome to 6

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3844]
https://github.com/pixiebrix/pixiebrix-extension/pull/3825

- [x] Release react-fontawesome 0.1.18 switch for Font Awesome 6: https://github.com/FortAwesome/react-fontawesome/releases
- [ ] Need to re-enable dependabot
   - see https://github.com/pixiebrix/pixiebrix-extension/pull/7602#issuecomment-1937562013

**Comment by fregante** [comment]
I don’t think dependency updates are ever stale, we do want improvements

**Comment by fregante** [comment]
- Blocked by https://github.com/webpack/webpack/issues/13865

**Comment by fregante** [comment]
I think the solution to this would be to publish a "pre-rendered" `@pixiebrix/icons` package instead. I had suggest this also when dealing with the many drawbacks of icon loading a few years ago:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4187
- https://github.com/pixiebrix/pixiebrix-extension/issues/2019

In short the `@pixiebrix/icons` package:

1. reads the list of the icons
2. exports it as a static array

I think that's just about it, maybe it could also include the CDN logic if that's what we want for Font Awesome too:

- https://github.com/pixiebrix/pixiebrix-extension/pull/5865


It's best to keep the build as slim and generic as possible instead of adding more and more config to webpack. This will also likely speed up the build.


---

I recently had similar pains in Refined GitHub so I published a "pre-rendered" fork of GitHub's Octicons, which let me avoid SVGR. Script here https://github.com/fregante/octicons-plain-react/blob/2b669cbd97c35966b07d47028e2c7054a28ad78b/scripts/prepack.sh
