### ISSUE TITLE
RFC: potential sidebar enhancements

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3850]
Ideas from the community:
- Would it be possible to open the URLs that I place in the sidebar inside the same tab instead of a new tab
- Would it be possible to resize the sidebar with the mouse
- Would it be possible to have a floating button to open/close a SPECIFIC sidebar more simply
- Custom submit handler for forms in sidebar
- Show modal/temporary form within sidebar
- Treat form as a button (what is this one?)

**Comment by fregante** [comment]
> * Would it be possible to open the URLs that I place in the sidebar inside the same tab instead of a new tab

Yes but that would "close the sidebar" and PB is unlikely to be able to open it again (unless it's on the same domain). Would that be acceptable for them?




> * Would it be possible to resize the sidebar with the mouse

Yes! I'd love to implement this. 

Kinda-related work:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2359
- suggested on slack: loading the sidebar via dedicated lightweight content script instead of our whole content script, so it can be opened immediately even without content script pre-injection

 



> * Would it be possible to have a floating button to open/close a SPECIFIC sidebar more simply

On the tabs I suppose?



> * Show modal/temporary form within sidebar

Don't we already? Literally "modal within the sidebar" is a terrible idea UX-wise, but we can show it as a temporary tab.
