### ISSUE TITLE
UX: Registry item does not exist error message does not provide enough information to users

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3858]
It's hard to tell what the problem is when an extension hits this error, because it doesn't give the value of the missing RegistryId, and no bricks show any errors.

**Comment by twschiller** [comment]
For context: our original approach to error messages was to not to include any details that might correlate with what sites the user was using. However, that has turned out to be a major blocker to customer support/success

The approach/philosophy has been adjusted to allow the following in error messages:
- Registry id
- Selectors
- Network request URL (only if enabled for the organization)

So in this case, we should include the registry id in the message
