### ISSUE TITLE
PLACEHOLDER: Provide informative guidance if button placement fails

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3902]
Context
---
- As a user, if button placement fails I get cryptic error message. Or the button is placed, but is not formatted wrote/there's no caption/etc.
- Possible mitigation: 
  - Point user to documentation on tips for placing buttons
  - Suggest to the user that they use the quickbar or context menu instead

Related Information
---
- Button Placement Guide in Documentation: https://www.notion.so/pixiebrix/Button-Placement-Guide-e162303d2ac14f99a08e1e4b5a005c04

Discussion
---
- Sometimes the button places but the style is wrong/there's no caption. At one point we had discussed generating alternative button placements and letting the user toggle between them to try to find one that works
- We've also done some work on automatically identifying good places to put a button, but that's not ready for general availability (Available as an option in the Skunkworks)

**Comment by corinnemayans** [comment]
Assigning to myself to work with Todd and Mike to thin-slice this so we can deliver incremental progress on this one.

**Comment by fregante** [comment]
This is something that could be fixed in the content script rather than in the page editor. The current behavior:

1. Start "element picking" mode
2. Click on the wrong element
3. "Element picking" mode exits
4. An error appears
5. Start "element picking" mode **again**

Whereas the picker itself should tell you that the selection was invalid and to try again. 

Additionally I implemented a more visual solution months ago but it has been hidden behind a flag since. I believe highlighting the valid elements to begin with would avoid absolutely any guesswork.
