### ISSUE TITLE
Error checking permissions when saving extension in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3910]
Context
---
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1659016286321749
- Impacted all users 7/28 UX testing

Steps to Reproduce
---
- Quick Start
- "After adding the initial extension brick (context menu brick) we configured that and then when we added the Translation brick and we tried to save it"

![image](https://user-images.githubusercontent.com/1879821/181524502-dcdf421c-b5c4-4346-881b-68e5086df094.png)

**Comment by BLoe** [comment]
@BALEHOK Assigned this to you. Let's use this ticket to track work for 1.7.3:

* Validate url pattern string-array fields for empty values
* Initialize the `Sites/APIs` field so that the helper buttons work when no entry has been added yet:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/2801308/182898872-94913d75-1ed9-4e38-aa00-bfad914f69ee.png">
