### ISSUE TITLE
Show registry id in blueprints screen to help distinguish bricks with the same name

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3954]
Context
---
- When 2 installable have the same name, it's not possible to distinguish between them on the Blueprints Screen
- The blueprints screen current shows "why" you're seeing a blueprint, e.g., because it's public or which team you're a member of that has access to the blueprint
- This comes up when someone has developed an extension locally and then clones it to share more broadly

Potential Ideas/Options
---
- Include the registry id in the hover for for the shared with/source
- Show the registry id on the card/list item if two installables have the same name
- Show the registry id always in list view (because there's more space?)
- Add an action to the ellipses menu to popup information about the installable

Discussion
---
- Quickest win is to include in an existing hover
- Sam, @MMirandi, and Brittany would be good people to chat about their considerations
- Also want/need to show personal singleton extensions vs. blueprints

Related Discussion
---
- Feedback from @MMirandi: https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1659465460965349
- Feedback from Brittany: https://pixiebrix.slack.com/archives/C02CN01JXAA/p1660193605803579

**Comment by icugideon** [comment]
@mnholtz Here's the fix for this. 
Showing the Registry ID by default on list view and on Hover for card view.

![image](https://user-images.githubusercontent.com/23545614/186657575-218ac175-616c-42e7-a8eb-2644e16c1c6e.png)


Interactive prototype [here](https://www.figma.com/proto/6J6JbIhjw0YVKaTP2Id4aK/Extension-Console?page-id=214%3A3676&node-id=402%3A6433&viewport=799%2C-833%2C0.16&scaling=min-zoom&starting-point-node-id=402%3A6433)

[Figma link](https://www.figma.com/file/6J6JbIhjw0YVKaTP2Id4aK/Extension-Console?node-id=214%3A3675)
cc @twschiller

**Comment by twschiller** [comment]
cc @corinnemayans
