### ISSUE TITLE
Regression: "This function must be called during a user gesture" when saving extension

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3961]
Environment
---
- 1.7.3-alpha.4

Context
---
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1659668799244099
- Chrome (and other browsers) require permissions requests to be triggered by a user action, e.g., clicking a button
- Sometimes async/await can throw off the chain of trust between the event and permissions request. (Firefox, e.g, I'm not sure if they fixed it or not, couldn't user async/await at all between; but we don't need to support Firefox at the moment)

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/183075222-ddb81ae9-e5eb-47a4-be3c-d78eb1bd6a99.png)

Discussion
---
- I think we have to use then/catch here (instead of async/await) because Chrome is losing track of the code flow  https://github.com/pixiebrix/pixiebrix-extension/pull/3952/files#diff-d395da390f30302d724d3c7ab9e4f11ba0b3744aff7c0eb8ab76ebba9aaa2d7bR140

Related PRs
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/3952

**Comment by fregante** [comment]
There's no easy fix for this. It's not about async/await, but rather just due to an internal timeout. Using `await sleep(100)` is allowed, `await sleep(3000)` isn't. See also:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3945

Possible solutions:

- speed up the refresh operation as a whole
- limit the refresh to exactly what's needed for this
- refresh before the user clicks, periodically, to reduce the chance of this happening
- drop the refresh altogether (i.e. find another solution to [#3951](https://github.com/pixiebrix/pixiebrix-extension/pull/3952))
