### ISSUE TITLE
PixieBrix triggers "PixieBrix could not run on the page" while using the Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4021]
Context
---
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1660427068171859

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/184511784-52b23aab-f04b-4737-ac57-461ba43723db.png)

**Comment by fregante** [comment]
This happens when the content script did not respond or if the injection failed. For this kind of errors, the console or background page console might contain more info.

**Comment by twschiller** [comment]
> This happens when the content script did not respond or if the injection failed. For this kind of errors, the console or background page console might contain more info.

OK, we're going to have to change the behavior because it's very confusing to users. (We've been getting reports of this randomly opening for enterprise users)

**Comment by fregante** [comment]
I do agree that the current delayed opening of a tab is rather annoying especially when clicked multiple times, but what's the alternative? 

More context:

- https://github.com/pixiebrix/pixiebrix-extension/pull/517

**Comment by fregante** [comment]
Found a repro:

1. Double-click the browser action

This happens because the "open" and "close" actions are not connected in any way. "open" waits for `sidebar.html` to load, but "close" prevents that from happening, without stopping the "open" action.

We need: 
- a better sidebar state handler to connect these two events
- AbortController support in webext-messenger so that a retry can be stopped
	- slightly related conversation inhttps://github.com/pixiebrix/webext-messenger/issues/38

## Demo

https://user-images.githubusercontent.com/1402241/185088348-a952930d-877a-4444-9c5e-33e05d43b088.mov

**Comment by fregante** [comment]
However that doesn't resolve the above issue, which is likely a direct consequence of this line:

https://github.com/pixiebrix/pixiebrix-extension/blob/ab93e5983748b1f8690979ae666eb453bff20a0b/src/pageEditor/panes/insert/GenericInsertPane.tsx#L66-L70

Which calls `ensureSidebar`, which for some reason fails to load/contact the sidebar.

**Comment by fregante** [comment]
There's no path between the pageEditor and that message. That messages lives **exclusively** in the browserAction handler. The issue described in the title is invalid, the page never "randomly opens." What happens is a consequence of:

1. User clicking the browser action
2. Two retrying mechanism kick in
3. Several seconds later the error appears

The error is also particularly bad because we ended up opening a new tab instead of using an alert as originally planned a year ago:

- https://github.com/pixiebrix/pixiebrix-extension/pull/517

I'll drop the alert. See following PR.
