### ISSUE TITLE
The page editor lets me add `@pixiebrix/form-modal` to a sidebar panel extension

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4025]
I think adding `@pixiebrix/form-modal` shouldn't be allowed:

<img width="223" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/184580609-a1ce266f-07bf-4479-bd23-6fbf1f126900.png">

https://user-images.githubusercontent.com/1402241/184580841-bb7b280e-d6b1-401b-b750-15264e30473e.mov

It almost makes sense as as "sidebar" form though:

https://user-images.githubusercontent.com/1402241/184580982-c002561c-41c9-46c9-9994-781db6a13a85.mov

The correct brick is likely `@pixiebrix/form`. What do you think? Feel free to close if this is fine

**Comment by twschiller** [comment]
> I think adding @pixiebrix/form-modal shouldn't be allowed:

You are correct there's two different forms of the brick: 1) the ephemeral form, and the 2) custom form that's a renderer

What missing here is:
- The analysis engine should show an warning/error that the brick type is not allowed there. (Really we should provide a warning in the main sidebar branch for all bricks that aren't marked "isPure", because the user doesn't have full control over renders of the panel)
- The Add Brick modal should grey out the brick with an explanation that it's not a good idea to add it in that location
