### ISSUE TITLE
Add alert for failed sidebar injection on the options page

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#4179]
Part of Onboarding Squad Sprint #3. Currently, if the user clicks the PixieBrix extension icon while within the options page, the extension does nothing. We'd like to add an alert similar to https://github.com/pixiebrix/pixiebrix-extension/pull/517 for consistency.

**Comment by corinnemayans** [comment]
Today, when the user is on the Options (Blueprints) page and clicks the PixieBrix toolbar extension button, nothing happens. I believe this is because it can't load the sidebar and it is already on the Blueprints page (otherwise, it would open the Blueprints page). Our hypothesis is that this is unexpected behavior and might make new users feel like PixieBrix isn't working properly. If they are clicking the toolbar extension button while on the Blueprints page, it is probably an indicator that they are confused about what to do. So, we can offer them a tip.

Proposed alert:
Title: PixieBrix Tip
Body: If you want to create a new blueprint, first navigate to the page you want to modify, then open PixieBrix in DevTools (Cmd+Opt+I).
Button: OK
(Note: Show appropriate shortcut based on OS.)

Looking for feedback on this approach @twschiller @mnholtz @BLoe @fregante

**Comment by fregante** [comment]
> Body: If you want to create a new blueprint, first navigate to the page you want to modify, then open PixieBrix in DevTools (Cmd+Opt+I).

That sounds good to me. 

This message can be displayed via the the old modal ([removed here](https://github.com/pixiebrix/pixiebrix-extension/blob/9ec292f56c00220f5e2de676105f23db78e36e32/src/layout/ErrorModal.tsx)) or any modal like it. This is what it looked like:

![184511784-52b23aab-f04b-4737-ac57-461ba43723db](https://user-images.githubusercontent.com/1402241/187653050-edce2c64-ba8d-4dbb-af39-67fb8651afa6.png)
