### ISSUE TITLE
Bad API request to 3rd party API via API Proxy not including error message from response in logs

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4217]
Context
---
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1661889573204619
- @orliesaurus was using our team's EasyShip credential
- It's not clear if 
  - 1) The API that @orliesaurus was using (EasyShip) does not provide any error information in its payload, or 
  - 2) Our API Proxy doesn't retrieve error information from bad response correctly
  - 3) Our client-side call to our API Proxy doesn't pass along error information to the logs correctly

**Comment by orliesaurus** [comment]
Since I've had this happen with multiple APIs therefore I suspect it's b. or c.

If I can add any context, the first time I resolved this issue by looking into what the payload I was setting is and realized I had made a typo.

The error response from the API was never shown to me - just "Bad Request".

I also tried to look into the HTTP console log from Dev tools for the extension and couldn't find anything useful unfortunately.
