### ISSUE TITLE
Broken Sidebar positioning on certain websites

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#4284]
Some websites, like tesla.com, produce Sidebar alignment issues (see below).

<img width="1204" alt="Screen Shot 2022-09-14 at 9 09 46 AM" src="https://user-images.githubusercontent.com/36575242/190206488-06384a8f-cd20-491c-b6c5-4e11df4c39f9.png">

[We discovered recently](https://pixiebrix.slack.com/archives/C023KL47XV4/p1663111680288609) that most of these occurrences are probably due to certain properties, like `filter` and `perspective`, applied to the `<body>` element [creating a new containing block](https://stackoverflow.com/questions/52937708/why-does-applying-a-css-filter-on-the-parent-break-the-child-positioning) for the Sidebar's `position: absolute` property, breaking the margin alignment.

In tesla.com's case, for example, this is the `perspective` property being applied to `<body>`.

Perhaps with this information there is a way we can fix the Sidebar alignment on websites like these.

**Comment by fregante** [comment]
It seems that merely appending the sidebar to `document.documentElement` instead of `document.body` fixes this specific case. I can send a quick PR.


However we're always at the mercy of the host website. Even if we place it in the Shadow DOM the website can still affect the shadow root element.

Eventually it would be nice to move to the native sidebar, should Chrome ever implement it:

- https://github.com/w3c/webextensions/issues/128
