### ISSUE TITLE
Tab state error in redux is a non-serializable object, but should be a string

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4409]
When the background context is invalidated, this error gets spammed to the chrome console:
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/2801308/194125458-a5e62230-3635-4199-963a-63f567f3705b.png">

We should just store the error message as a string, not the `Error` object, in redux.

**Comment by twschiller** [comment]
> We should just store the error message as a string, not the Error object, in redux.

Double-checking here -- are we just missing a call to serializeError somewhere? In general, PixieBrix needs to pass around error-like objects for telemetry to work properly

**Comment by twschiller** [comment]
@BLoe Looking at this now (post merge), IIRC the old type of editorSlice was probably to match the Formik "status" which takes a single string for the whole Formik form.

I'm OK revisiting using a string in the state. In general, supporting a serialized error is more general (because we can store details, etc.). 

Is there anything to discuss on this still? Looks like it was resolved while I was OOO?
