### ISSUE TITLE
Selection/Link text coming through as undefined for Context Menu targeting link

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4536]
Context
---
- Seen on 1.7.11

Steps to Reproduce
---
- https://www.notion.so/pixiebrix/Content-Management-e28a500ef40547eaaed6e8ce9827d080
- Activate https://app.pixiebrix.com/activate?id=@pixies/content-management-demo
- Visit [TripAdvisor Cancun Hotel](https://www.tripadvisor.com/Hotel_Review-g150807-d219145-Reviews-Marriott_Cancun_Resort-Cancun_Yucatan_Peninsula.html) and right click on a name

Discussion
---
- In the preview for the output it appears, but doesn't make it's way in the actual run of the brick. The extension drops in "undefined" in the Salesforce search box

**Comment by fregante** [comment]
In which brick is the issue here? I haven't tried the specific blueprint because it requires 2 external keys.

I tried with a raw brick and the context menu seems to pick up the selection correctly, as long as there's any selection.

Site note: links are automatically selected on right click (only on macOS, I think)

https://user-images.githubusercontent.com/1402241/211511944-6fabde00-b3f0-4c68-b8b4-bcef62febba7.mov
