### ISSUE TITLE
Infinite request loop if `/recipes/` request fails on blueprint page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4775]
Steps to Reproduce
---
- Observed on 1.7.15-beta.2 when testing the partner OAuth2 flow when our test CR was down

Extension Console
--- 
![image](https://user-images.githubusercontent.com/1879821/206073047-ac3e4b6b-7812-4f15-a4ae-4c8c8cc36777.png)

Control Room
---
![image](https://user-images.githubusercontent.com/1879821/206072969-d28973c0-0f35-4bf3-80a4-624c738563ef.png)

**Comment by fregante** [comment]
This appears to have been resolved, also because the API was changed

- https://github.com/pixiebrix/pixiebrix-app/issues/2184#issuecomment-1867151616

Here I blocked the specific URL in the dev tools and I think it only requested it twice

<img width="1344" alt="Screenshot 7" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/b238e75a-b401-4ecc-9785-87e6fd29e901">
