### ISSUE TITLE
Improve error reporting infrastructure

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#580]
- [ ] Define which errors are worth reporting
- [ ] Unify error display (user, console, rollbar) and context (local, background)
- [ ] Have the global error handlers deal with errors instead of manually adding `.catch(report)` unless there's an `await` before it and we explicitly want to catch it
- [ ] Never pass serialized errors around, deserialize them as soon as possible
- [ ] Have a helper "error decorator" to add more context, or extend reportError
	```js
	.catch(describeWarning('Was trying to connect'));
	```
	```js
	.catch(describeError('Was trying to connect'));
	```
	```js
	.catch(error => reportError(error, {cause: 'Was trying to connect'});
	```

Code like this should be greatly simplified:

https://github.com/pixiebrix/pixiebrix-extension/blob/cd85e8fd6314ecb6995150fd01e59f1af132375b/src/extensionPoints/contextMenu.ts#L68-L78

https://github.com/pixiebrix/pixiebrix-extension/blob/7d266cfb72d33d27425f9c8223a0f91d8c565366/src/blocks/combinators.ts#L423-L452

https://github.com/pixiebrix/pixiebrix-extension/blob/7d266cfb72d33d27425f9c8223a0f91d8c565366/src/background/contextMenus.ts#L75-L89

**Comment by twschiller** [comment]
## Considerations

### Minimize passing around serialized errors

User code should pass around real errors. Serialization should happen under the hood for message passing across boundaries

### Caller is responsible for handling the error

If the content script calls into the background page and an error occurs in the background page (e.g., a failed network request), the content script handles the error. (The handler will involve sending another message to the background page to record/report the error to Rollbar)

Same for if the dev tools is performing an action in the content script (via message passing through the background page)

### Automatic error handling

Where possible, use top-level handlers to simplify error handling code (including unhandled promise rejections).

Use error metadata (the error class, additional properties on the error) to decide how to record the error, what level to report it as, etc. See current handling of "Business" vs. "ApplicationErrors": http://github.com/pixiebrix/pixiebrix-extension/blob/619f9ee0f056dbd083ae3cc35352f28c257a5f9f/src/background/logging.ts#L187-L187

Where to show the error will depend on if the user is on an extension page (e.g., the options page, has the side bar open, is in the dev tools, or are just on a normal page)

### Try to preserve a meaningful stack trace

Stack traces are trick for cross-boundary calls. E.g., what should the call stack look like if the call from a content script fails on the background page?

### Browser automation testing support (Selenium/Puppeteer/etc.)

The browser automation testing framework we choose needs to be able to query if any errors have occurred (so that it can expect an error to have occurred, or not errors to have occurred)

OK to have code that only runs in the test environment to support this
 
### Associating errors with bricks

Need to associate errors with specific bricks, blueprint deployments, etc. See: http://github.com/pixiebrix/pixiebrix-extension/blob/619f9ee0f056dbd083ae3cc35352f28c257a5f9f/src/background/logging.ts#L196-L196

### Unwinding `ContextError`s

We have an error wrapper for adding additional context to an error:http://github.com/pixiebrix/pixiebrix-extension/blob/619f9ee0f056dbd083ae3cc35352f28c257a5f9f/src/errors.ts#L67-L67

The problem with it is that by adding extra layers (sometimes multiple layers) of context, the original error message and stack gets lost or hard to find

### Network Requests

* Network request messages (e.g., 400 Bad Request) need to be passed through the UX in a more meaningful way
  * Normal requestions 
  * Requests that go through the authentication proxy: http://github.com/pixiebrix/pixiebrix-extension/blob/619f9ee0f056dbd083ae3cc35352f28c257a5f9f/src/background/requests.ts#L190-L190
   
### Extension loggers

Extension points all take a logger, which automatically track the context of the log message. (And can be used to create sub-loggers with a more specific context. These loggers include an `error` method

**Comment by fregante** [comment]
Found a problem:

- https://github.com/sindresorhus/serialize-error/issues/48

I think that means that this line hasn't been working as expected for cross-boundary errors:

https://github.com/pixiebrix/pixiebrix-extension/blob/37efea1f7e722d67fb70c2df969b66a2681490da/src/errors.ts#L83-L92

**Comment by twschiller** [comment]
> Found a small problem:

These sorts of corner cases would be good candidates for Jest tests in our test suite

**Comment by fregante** [comment]
Idea: 

- Wrap errors when they cross boundaries, e.g. ContentScriptContextError
- Wrap communication errors, e.g. MessagingError, so you know when an error is coming from the current context and is exactly because the communication failed

If we want to transfer error across boundaries the stack starts to lose meaning because suddenly background.js is throwing an error with a stack that does not include any files in background.js (I think?)

The newest way to wrap errors seems to be the .cause property: https://github.com/tc39/proposal-error-cause

In short, I think it's something like:

```js
if (isErrorObject(response)) {
	const crossBoundaryError = new ContentScriptContextError(response.message);
	crossBoundaryError.cause = deserializeError(response);
	throw crossBoundaryError;
}
```

Notes:

- This will keep the original error and its stack intact
- The proposal is still in Stage 3 so we'd have to manually set the `cause` property
- This might not be understood by Rollbar

Alternatives for the wrapping:

- [AggregateError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError), also mentioned in that proposal, but already supported by Chrome and Firefox
- Something to merge the stack of append the stack/message of ContentScriptContextError to the `response`’s stack/message in order to preserve both
