### ISSUE TITLE
Fix animations on loading indicators in `PanelBody` for sidebar mods

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5825]
Follow-up to #5820

* Loaders don't animate/"spin" properly
* We'd like to add a fade-in animation to them as well
* Possibly consolidate the loading indicators for all bricks within a panel?
* Config option for a brick to hide the loading indicator?

**Comment by fregante** [comment]
This is because that `<Loader>` appear in a shadow dom and the CSS module class isn't loaded in there.

I think the right way to deal with this is to use our `<Stylesheets>` component, which we already use to load bootstrap. 

If shadow dom is a common occurrence, we should create a component that just loads our entire style in there rather than having to manually wrap each component in `<Stylesheet bootstrap>`

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/293e4df9-8971-4c18-af36-4af31f51e2ba)
