### ISSUE TITLE
Bug: Mixpanel Extension events not preserving/reporting the right timestamp

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5970]
For events being reported in the extension, we should be recording the timestamp of when the event itself occurred. I've noticed that timestamps for events are often the same for a cluster of events, or event timestamps are being included out of logical order of when the events should actually be happening.

**Comment by twschiller** [comment]
I noticed this to when doing the process mining POC. I had ended up needing to include the timestamp in the process mining mod because otherwise batches of events would all get the same timestamp


Related Code
---
- https://github.com/pixiebrix/pixiebrix-app/blob/ee736acf948c15967e9857d51f7c6abcc13af2e1/telemetry/views/event.py#L75-L75
- Process Mining POC: https://github.com/pixiebrix/pixiebrix-app/pull/3231/files#diff-58e778e0c536239c71ea80140a7b9269c52aab8a3149aef6858cf2214e22e259R84

**Comment by mnholtz** [comment]
Closing in favor of duplicate: https://github.com/pixiebrix/pixiebrix-app/issues/3861
