### ISSUE TITLE
Content script doesn't load in srcdoc iframes causes message retries

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6206]
Context
---
- See comment/screenshot here: https://github.com/pixiebrix/pixiebrix-extension/pull/6198#issuecomment-1663880196

Steps to Reproduce
---
- Turn on `WEBEXT_MESSENGER_LOGGING=true`
- Visit: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
- Add a Log to Console Brick with "All Frames" and run from the Trigger from the Page Editor
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/4e3ef60e-2ea1-4fed-8c26-ce11d6825868)

Screenshots
---

There are multiple "received in content script messages" after the content script responds
 
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/9788c6f6-cb67-4f67-9b1a-10dc9e6256be)

Discussion
---

There might be extra copies of the content script in top-level frame. (But only one of them has any logs in the console for the context). I think these were injected by the Page Editor

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/e3cf07fa-0128-4c1e-9a7a-125418686711)

It looks like it's the srcdoc frame, what's interesting is that the brick is not actually being run there though (there's no "Hello" message)

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/e01cdc35-5a0d-43aa-9754-1fc81c2a7162)

**Comment by fregante** [comment]
> I think these were injected by the Page Editor

I don’t think that’s possible anymore, right? The injection is entirely handled by the browser now. There’s no chance that scrips are injected twice (unless the extension is reloaded). The duplicates you see are probably only due to the dev reload. 

What does it look like in the background page? My guess is that each of those message has a sender in the background page

**Comment by fregante** [comment]
The messages are multiple retries of the same message from the background script,  this can be also seen in the background:

<img width="567" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/7137ecca-4a34-4190-a32e-a90899fa0f08">

I'm having a hard time debugging this issue because the developer tools appear to ignore the breakpoints _in that iframe_ 🤔 

My best guess at the moment is that the application is triggering a silent fatal error and the message doesn't even get to respond with that error. My second guess is that the error happens earlier than the method registration, so the code reaches "No handler registered" and moves forward as a "retriable scenario"

**Comment by fregante** [comment]
As you mentioned before, all the `http` checks in the app should at least be updated to include `about:`, for example:

https://github.com/pixiebrix/pixiebrix-extension/blob/294337ff7761eb4561a610b0df33c0741d267410/src/permissions/permissionsUtils.ts#L184C1-L186

**Comment by fregante** [comment]
Indeed no methods are being registered in that context:

<img width="715" alt="Screenshot 7" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/877890de-04b8-4a50-8eb7-5e2051ec05c0">



<img width="731" alt="Screenshot 6" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/007b2c8c-d5b0-45de-9c5f-d3765ed7a81e">

**Comment by fregante** [comment]
`contentScriptCore: init` is not in the console, probably `import("contentScriptCore")` is failing entirely

https://github.com/pixiebrix/pixiebrix-extension/blob/294337ff7761eb4561a610b0df33c0741d267410/src/contentScript/contentScriptCore.ts#L51C1-L54

Is the `@cfworker/json-schema` error related? `new URL('about:srcdoc').origin === 'null'` so this is probably breaking a lot of expectations everywhere. I can work on this issue until it's resolved if you confirm.

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/b9b7f451-6ce3-4aaa-8733-f77e3f6e1365

**Comment by twschiller** [comment]
Since it's a module-level import, you're right it'd be preventing the contentScript entry point from loading

Here's the code: https://github.com/cfworker/cfworker/blob/main/packages/json-schema/src/dereference.ts#L68

Would be great if you could create an issue/PR in the cfworker repo. We will likely have to vendor that file in the meantime

**Comment by fregante** [comment]
I just noticed that this is still open and assigned to me. If it's still an issue even after that PR I can keep looking into it

**Comment by twschiller** [comment]
Thank you for checking, I think we just forgot to close it. Closing now
