### ISSUE TITLE
Error initializing contentScript	

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6245]
Context
---
- https://app.rollbar.com/a/pixiebrix/fix/item/pixiebrix/4847?showOccurrences=true
- Causes:
  - This target is not in a frame
  - Cannot read properties of null (reading 'append')
  - `chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/pageScript.js`
  
Triage/Discussion
---
- These may be benign for use cases, but they're flooding Rollbar with warnings/errors
- Some of the problems may have already been addressed in 1.7.36 with fixes for `http:` and `about:` protocols

**Comment by twschiller** [comment]
Example of an error, which can be seen in the background page PixieBrix tries to inject the contentScript into the frame that GAPI adds:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/c4b3a113-87e5-406c-ba2e-38d30f9879ba)

**Comment by BLoe** [comment]
This `content-sheets.googleapis.com` seems to be a frame mounted in the generated background page for the extension.

In our manifest content script settings, we are using the `"all_frames": true,` flag in order to allow our content script to run in iFrame contexts. The problem here is that now the contentScript url matchers return true for a `https://` url in a frame _within_ the `chrome-extension://` generated background page. So our content script is attempting to mount on this frame and running into issues mounting the navigation handler (which doesn't even make sense to attach to the generated background page...)
