### ISSUE TITLE
Context menu items showing for mods that are not active

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6443]
https://pixiebrix.slack.com/archives/C0436P48QHY/p1694551866880489

**Comment by fregante** [comment]
From slack:

> sticky context menus have been like playing whack a mole

We should move the registration out of the content script, content script should not be registered on page load (which is when the content scripts run)

I think this bug happens because:

1. the mod is updated/removed in the background
2. when the content script runs, it just tries to register the context menu with the latest information, it has no recollection of the previous context menu that should now be removed

If context menus were handled entirely by the background page, then a mod update in the background would automatically be followed by "unregister all context menus, then register again"

Then the page editor can register the dynamic context menus directly, perhaps via a special `contextMenuId` that starts with `dynamic:` so that they can be recognized and handled better.

**Comment by fregante** [comment]
Disregard. It looks like `ensureContextMenu` is already being called by the background page on load, which is good. 

However the content script _also_ calls it at every page load, which should probably be dropped and let the background page (and page editor) deal with registration independently:

<img width="958" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/a2a1dadb-d091-46b4-a5a9-410d8d1c900f">
