### ISSUE TITLE
Confusing all_frames behavior--the "Extract from Page" result is excluded by errors due to multiple matches

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6536]
https://pixiebrix.slack.com/archives/C0436P48QHY/p1695747377760369

**Comment by twschiller** [comment]
Steps to Reproduce
---
- Add the "Extract from Page" brick
- Set target to "all_frames"
- Add a selector that matches multiple elements in a frame, e.g., `a` but don't set "All Matches"

Actual Behavior: frames that the brick errors out on are not included in the responses
Expected Behavior: TBD, potentially the whole brick should error out in this case
