### ISSUE TITLE
Notes about `eslint-plugin-security`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#670]
(This is a non-issue, just for discussion purposes)

`security/detect-object-injection` has a lot of false positives. Could a solution be in this long SO answer? https://stackoverflow.com/q/57960770

Related (but no solution here)
- https://github.com/nodesecurity/eslint-plugin-security/issues/21

**Comment by twschiller** [comment]
I don't mind having to write warning suppressions with justification. The main thing is getting the number of down to a level where we're not in a "boy who cried wolf situation" during development and PR review

In "normal" application code, we should by and large be able to use `Map` or another safe alternative

The main areas where `Map` wouldn't be feasible right now:
- Redux code: because the state has objects keyed by dynamic fields. Mitigated by 1) validation of ids, 2) use of Immer by Redux tool kit? State shape could be re-written, bu persisted state would need to be migrated
- Brick templating: this is actually the area where prototype pollution and similar concerns are relevant. We can/should eventually be executing templating in the `sandbox`
- "Page script" getters and setters: another area we can't avoid, and where prototype pollution is relevant. This can't be sandboxed. For getters, we should be freezing/sealing. For setters we should be sanitizing property name and checking for hasOwnProperty, etc.

**Comment by fregante** [comment]
Closing as my last attempt at this was not merged: 

- https://github.com/pixiebrix/pixiebrix-extension/pull/3394
