### ISSUE TITLE
`CONNECT_PAGE` doesn't seem to be registered among the page script handlers

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#691]
_Originally posted by @fregante in https://github.com/pixiebrix/pixiebrix-extension/issues/490#issuecomment-868427229_

`CONNECT_PAGE` doesn't seem to be registered among the page script handlers. Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/578

It seems that it's because `messaging/external.ts` is not included in `script.js` and if I try to include I get a rollbar error which causes the whole file to fail, it seems.

```
 Uncaught Error: Permission denied to access property "_rollbarOldOnError"
    captureUncaughtExceptions moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:63981
    setupUnhandledCapture moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:63981
    m moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:63981
    init moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:63981
    ts moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:67396
    __webpack_require__ moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:72586
    ts moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:64173
    __webpack_require__ moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:72586
    ts moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:66258
    __webpack_require__ moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:72586
    <anonymous> moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:72680
    <anonymous> moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:72862
    <anonymous> moz-extension://fb57a464-0fcd-bd4d-8c0c-7da43ba6341a/script.js:72864
```

**Comment by twschiller** [comment]
I don't think the "page script" should be involved at all. And that we probably just need the page script to drop the message. Perhaps this is a symptom of 1) module coupling, 2) a module with a side effect on import

I think what's happening is:
* For Firefox, CONNECT_PAGE goes uses our externally_connectable polyfill which uses: `document.defaultView` and `window.addEventListener` for the messages
* The page script and content script communicate via the same channel. So the page script is also getting that message. It should be dropping it though since a handler wouldn't be defined for it: http://github.com/pixiebrix/pixiebrix-extension/blob/263412d518756cb382bde0569d1e79ffd41b963c/src/pageScript/protocol.ts#L76-L76

I also wonder why the page script is trying to access Rollbar (if that's what the error is suggesting)? It shouldn't be as Rollbar won't exist within the JS environment/context for the host page

**Comment by fregante** [comment]
Closing this because I think it's a duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/682

I thought that pageScript was required to proxy messages for externally_connectable, but I think that's not the case.
