### ISSUE TITLE
Selecting one of multiple forms in a Render Document selects all of them

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7019]
## Describe the bug

When working with embedded forms in a Sidebar starter brick, if multiple forms have been added, then selecting a form in the Brick Actions selects all of the forms.

## To Reproduce

1. Add a sidebar panel starter brick
2. In the Render Document, add a form
3. Add additional forms
3. Click on the `Custom Form` in the pipeline

## Actual behavior

All of the forms are highlighted. Modifying the Step Name updates the name of the last form.

## Expected behavior

Only the form clicked on is highlighted. Modifying the Step Name (or any other configuration) affects the correct brick.

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/d654bb43-d15f-4109-b68a-4c0b3ed5b7b2)

## Desktop (please complete the following information):

- Extension Version: 1.8.3, 1.8.4-beta.2

## Additional context

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1701285319033919
- It does not matter if the forms are in separate rows/columns
- It does not matter if there are other bricks in between

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Selecting a form in the Render Document highlights only that form**
  - Given a sidebar panel starter brick with multiple forms added
  - When I click on a form in the Render Document
  - Then only the clicked form should be highlighted

- [ ] **Scenario 2: Modifying the Step Name affects the correct form**
  - Given a sidebar panel starter brick with multiple forms added
  - And a form is selected in the Render Document
  - When I modify the Step Name of the selected form
  - Then the Step Name of the selected form should be updated

- [ ] **Scenario 3: Modifying any configuration affects the correct form**
  - Given a sidebar panel starter brick with multiple forms added
  - And a form is selected in the Render Document
  - When I modify any configuration of the selected form
  - Then the selected form should be updated with the modified configuration

- [ ] **Scenario 4: Selecting a different form in the Render Document highlights only that form**
  - Given a sidebar panel starter brick with multiple forms added
  - And a form is already selected in the Render Document
  - When I click on a different form in the Render Document
  - Then only the newly clicked form should be highlighted

**Comment by fregante** [comment]
I think this is just non-unique `key`  being set to all, right? I assume it's the result of using the index `i` from a `.map() as key without further modifications.

**Comment by fregante** [comment]
If nothing else more urgent comes up I'll look into enabling that rule now, maybe this issue will be resolved.

**Comment by fregante** [comment]
No that's not due to `map`, the `key` is missing entirely and I can't locate the place where it should be added.

## React DevTools

View:

<img width="233" alt="Screenshot 17" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/5bb1081b-4403-4b49-b139-2812391b5182">

The key is missing:

<img width="301" alt="Screenshot 15" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/720d1973-52e2-4938-b364-31f4dafb9804">


## Console

Actually there's a console error for this issue:

<img width="1006" alt="Screenshot 14" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/063a054d-9f7d-4d4b-a9dc-036064cd23b4">

**Comment by twschiller** [comment]
The hook uses the [instanceId](https://github.com/pixiebrix/pixiebrix-extension/blob/cc63ffc68cf7f6c9a9ee37bedf902b4a9a4186c3/src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx#L452-L452) as the key for bricks. Looks like the instance id is missing for the brick when added via the Document Builder 3-dot menu: 

<img width="246" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/ae4ff3b0-08a8-4af0-
a22f-7de8a4b53e63">

I'm pretty sure the bug is we're not adding an instance id here: https://github.com/pixiebrix/pixiebrix-extension/blob/cc63ffc68cf7f6c9a9ee37bedf902b4a9a4186c3/src/components/documentBuilder/createNewElement.ts#L82-L82
