### ISSUE TITLE
Ensure background modules use `chrome.storage.session` for storing persistent information

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7181]
Context
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/7171#issuecomment-1867659577

Definition of Done
---
- Background modules use session storage where required

Discussion
---
- Lint rule can enforce usage directly in modules
- It would be harder to do transitive dependencies. We'd need to mark a file as using module variable and then look at the module dependency tree
- Can't use a grep rule on the JS output for background.ts because there'd be no good way to suppress false positives?

**Comment by fregante** [comment]
I think generally we should stop relying on the background for almost everything except the bare minimum. I opened an issue for this:

- https://github.com/pixiebrix/pixiebrix-extension/issues/7182

As mentioned in https://github.com/pixiebrix/pixiebrix-extension/pull/7180#issuecomment-1867771180, I don’t think we can actually _ensure_ or prevent this from happening because static analysis can only get us so far (e.g. we might be relying on scope or even inside external dependencies)



> * We'd need to mark a file as using module variable and then look at the module dependency tree

This is a tough problem. I know it's what `eslint-plugin-import` does and some of its rules are super slow. Particularly, this needs to work in reverse as far as I know:

1. eslint encounters a file
2. eslint-plugin-import (presumably) looks at all the files being linted and builds the dependency tree from there
3. only then the file can be analyzed

I'm not sure if this is a job for ChatGPT-eslint and I can't think any other complete automation. However the lint rule in https://github.com/pixiebrix/pixiebrix-extension/pull/7180 can be manually extended. I'll leave a comment there.

**Comment by fregante** [comment]
I presume this is done. I can take a manual look at the /background files but I think the rule already covers most issues.

**Comment by twschiller** [comment]
> I presume this is done

Yep, let's close it out
