### ISSUE TITLE
Slice 3: Move toolbar icon badges for background script errors under env flag

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7312]
https://www.notion.so/pixiebrix/Phase-2-Add-Brick-for-Setting-Badge-in-Toolbar-04b12e551113443b9218317744dd864f?pvs=4#ec0aedbd082049a78079754432d3dcff

**Comment by fregante** [comment]
I'd vote to use system notifications instead, it'd be quite useful.

The change would probably just be:

- in `manifest.mjs`: add `notification` permissions `if !isProduction`
- in `errorsBadge.ts`: use `chrome.notifications.create()` instead of `browserAction.*` calls (it'd make the file much simpler rather than longer)

**Comment by twschiller** [comment]
> I'd vote to use system notifications instead, it'd be quite useful.

I'm OK with giving it a try. FWIW, I have Chrome system notifications off. Not sure if other developers do to

**Comment by fregante** [comment]
Yeah I'm ok either way. I think I have notifications enabled but I only use chrome for development

**Comment by mnholtz** [comment]
> I'd vote to use system notifications instead, it'd be quite useful.

I like the idea; also on board with giving it a try
