### ISSUE TITLE
MV3 release build not linking with with app.pixiebrix.com

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7468]
## Describe the bug

- The linking implemented for https://github.com/pixiebrix/pixiebrix-app/issues/4523 doesn't appear to be working on 1.8.8-alpha.2

## To Reproduce

- Toggle off your MV2 build (so the code to update the DOM doesn't conflict)
- Activate the MV3 build

## Actual behavior

The extension is updating the DOM as expected:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/0a56b0f9-c64c-4806-96d8-b85bc89590e4)

The extension is not being detected/linked:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/b868552b-5a11-4ca1-897a-0c1811489ce7)

## Expected behavior

When opening `https://app.pixiebrix.com` with the extension running, the extension is linked

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/e1ecdf65-2781-42b4-b65c-1811663af7d2)

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.8-alpha.2

**Comment by johnnymetz** [comment]
Note, linking works when using the MV2 `CHROME_MANIFEST_KEY`. It doesn't work when using the MV3 `CHROME_MANIFEST_KEY`.

The problem is happening here: `browser.runtime.getManifest()` returns `null`

https://github.com/pixiebrix/pixiebrix-extension/blob/2f3a2f5c8b21f7c6ad81e505f9a6cbc717959bd8/src/background/messenger/external/api.ts#L27-L29

Still trying to figure out why. It's returning a full manifest object for MV2.

**Comment by fregante** [comment]
> The problem is happening here: browser.runtime.getManifest() returns null

I don’t think that can happen, this is more likely to be a messaging error 🤔 (due to a mismatch in key in the app or in the "externally connectable" list of hosts)
