### ISSUE TITLE
Switching the mod in a deployment leaves both activated

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7475]
## Describe the bug

When updated which mod is deployed as part of a deployment, the users receiving the deployment end up with both deployments activated

## To Reproduce

1. Create a new deployment
2. Add a mod to the deployment
3. Add a test group to the deployment
4. Activate the deployment for a user in the test group
5. Change the mod that is packaged in the deployment
6. Activate the mod for the deployment

## Actual behavior

Both mods are activated for the users in the group

## Expected behavior

The new mod should be activated and the previous mod should be deactivated.

## Desktop (please complete the following information):

- Extension Version: 1.8.7

## Additional context

See https://pixiebrix.slack.com/archives/C0436P48QHY/p1706546408276149 for additional context

**Comment by twschiller** [comment]
This occurs because uninstall for re-activation is based on package id. It instead needs to be based on the deployment Metadata

The following locations need to account for the mod id potentially changing:
- https://github.com/pixiebrix/pixiebrix-extension/blob/f4926d4ec5ab2370327c6f8e09c3c8769677ddf2/src/background/deploymentUpdater.ts#L230-L230
- https://github.com/pixiebrix/pixiebrix-extension/blob/f4926d4ec5ab2370327c6f8e09c3c8769677ddf2/src/extensionConsole/pages/deployments/activateDeployments.ts#L42-L42

Related Code
- https://github.com/pixiebrix/pixiebrix-extension/blob/f4926d4ec5ab2370327c6f8e09c3c8769677ddf2/src/types/modComponentTypes.ts#L111-L111

**Comment by twschiller** [comment]
Logic needs to be taken into account for both the background updater and the Extension Console

Related Issues:
- https://github.com/pixiebrix/pixiebrix-extension/issues/8131#issue-2219237011

**Comment by twschiller** [comment]
@mnholtz the code will still need to account for removing the package if it was previously installed as a non-deployment and then becomes managed

**Comment by mnholtz** [comment]
> the code will still need to account for removing the package if it was previously installed as a non-deployment and then becomes managed

@twschiller I looked into this. It seems like this conflicts with existing logic:
https://github.com/pixiebrix/pixiebrix-extension/blob/bugfix%2F7475_fix_switch_deployed_mod/src/utils/deploymentUtils.ts#L94-L105

What exactly do we expect to happen in situations where a dev deployed a mod they made? And then switched the mod in the deployment? In other words, should we get rid of the check I referenced above?
