### ISSUE TITLE
MV3 - SidePanel error running mod

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7514]
## Describe the bug

After installing the Notices/Announcements dogfood mod and viewing in the Side Panel, the below error is visible at first. After time, the expected view does load in.

## To Reproduce

1. Go to https://app.pixiebrix.com/activate?id=@pixies/template/notices
2. Activate the mod (no need to configure)
3. Navigate to any website
4. Open the Side Panel
5. View the Notices/Announcements panel

## Actual behavior

<img width="770" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNndsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4141ab3e8b80d677199cbb6df6af038749bc999/image.png" alt="image.png" />

## Expected behavior

<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3c93cdc698a8b1da50ce9795a67f0911d1ee765/image.png" alt="image.png" />

## Desktop (please complete the following information):

- Extension Version: `main` as of 2/2/24

**Comment by fregante** [comment]
I've seen this when switching between manifests. Make sure you do a full background page reload. 

Still worth investigating though, because I also saw that message and then saw it disappear after a second or two, so something is definitely loading slowly.

**Comment by grahamlangford** [comment]
I had been running mv3 for a while, so I'm know the background page was running well.

I did just try to replicate and couldn't. 

Had a somewhat similar problem with the `Append to Google Sheets` brick running extremely slowly, but then it started working normally as well.

**Comment by fregante** [comment]
I haven't been able to repro. I think we can only work on this in the exact moment it appears. I haven't seen it in at least 2 weeks.

I think this is only dependent on the MV3 because the sandbox is enforced there, but otherwise the background worker shouldn't affect it.


<img width="683" alt="Screenshot 4" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/96fa99d1-e3db-4c5d-8127-27fab3285ca7">

The message is generated here, but I don't see anything that should take a substantial amount of time. Sandbox.js is only 800KB _including the sourcemaps_ (plus the deferred dependencies, which shouldn't affect the `load` event)

https://github.com/pixiebrix/pixiebrix-extension/blob/f2b8271d45d884d37a121da36f6da69323279986/src/utils/injectIframe.tsx#L38-L56

**Comment by grahamlangford** [comment]
Agreed. I haven't seen it since. We'll just have to keep an eye out.

**Comment by fregante** [comment]
<img width="337" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/824a1f62-478d-4f07-8eca-8174801ceb85">

I experienced it again:

1. Running MV2
2. Switch to MV3 build
3. Click "Reload extension"
4. Open sidebar (previously on the AI Copilot tab)
5. See error


Interestingly, there's no iframe in the body at all, so I wonder if `waitForBody` is somehow failing (???) or if something is removing the frame before it finishes loading.


<img width="223" alt="Screenshot 12" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/ccd62448-454d-4e65-8b99-0cc6a5b441f8">



Unfortunately, after a couple of console.logs and reloading it loaded fine, but I see no SANDBOX calls at all in that case. So now I'm wondering why the first load used the sandbox and the second one didn't

**Comment by twschiller** [comment]
Closing for now as it appears to be related to upgrading from MV2 to MV3. Will reopen if it comes up during dogfooding
