### ISSUE TITLE
[Spike] Support custom branding browser action icon

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7555]
## Phase Spec

- https://www.notion.so/pixiebrix/Support-custom-branding-browser-action-icon-724f27a392be48dca4d9450edc701ba6

## Acceptance Criteria

- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Support custom browser action icon` epic 
- [x] Tech Lead notified for prioritization

**Comment by fregante** [comment]
Note that we have logic around the icon, to help us immediately see when the background page completely failed loading:


https://github.com/pixiebrix/pixiebrix-extension/blob/7b1d78010ad896aa08b951924a12afa78da05012/src/background/activateBrowserActionIcon.ts#L20-L25

I opened a PR to simplify this logic in:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7600

**Comment by fregante** [comment]
As for the [gist](https://gist.github.com/fungairino/c6e477c76dadafe6b174bd2e6fa4b7c9), I don’t think the `readAsDataURL` conversion is necessary. Once you `fetch` and read its `blob`, you can already paint it to the canvas safely. In MV3, actually you don't need the canvas at all.

The "tainted canvas" restrictions (should) only apply to images loaded via `<img>`, because they can be loaded across domains without CORS. `fetch` will fail immediately if CORS/CORB rules are breached.

It should look like this, with MV3 service worker support:

```js
async function blobToImageData(blob) {
  if (typeof createImageBitmap === 'function') {
    return createImageBitmap(blob); // MV3
  }

  // Load into image
  const img = new Image();
  img.src = blob;
  await img.decode();

  // Paint on canvas and return
  const canvas = new OffscreenCanvas(16, 16);
  const context = canvas.getContext("2d");
  context.drawImage(img, 0, 0);
  return canvas.transferToImageBitmap();
}

async function getImageData(url) {
  const res = await fetch(url);
  return blobToImageData(await res.blob());
}
```

**Comment by fungairino** [comment]
Thanks for sharing @fregante. I modified your gist to return a ImageData object since that is what is needed for the browser setIcon API. 

https://gist.github.com/fungairino/59d7ba0383e04e81ef562a91ac6a6b42

Additionally it seems like `createImageBitmap` has issues with SVG's. We will need to investigate some work-around, maybe using something like this: https://github.com/Kaiido/createImageBitmap. This blocks MV3, but should not block the release this week.

**Comment by fregante** [comment]
ImageBitmap is the same as ImageData I think?

**Comment by fregante** [comment]
I assumed they were different names for the same thing. 

Yeah I can look into it later as part of the MV3 work
