### ISSUE TITLE
PixieBrix was restarted toast showing on pages even if user has no mods

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7620]
## Describe the bug

- PixieBrix 1.8.8 is showing a context lost toast on pages even if there's no mods activated
- Seen on client call when client was using a VDI with PixieBrix force-installed in Chrome

## Triaging

- This comes up in enterprise scenarios where user has other tabs open when the first log into PIxieBrix. (Because in their VDI environment there's they start with some tabs open)

## To Reproduce

Steps to reproduce the behavior: (I still need to reproduce this locally; just capturing what I think we main elements from the customer call)

1. Have PixieBrix extension installed but not authenticated in clean Chrome profile
2. Open a website in a tab
3. In a separate tab, authenticate with PixieBrix (with a team account that's not assigned any mods)
4. Go back to the original tab and interact with the page

## Discussion

- Our `onContextInvalidated` listeners [seem to not immediately show the invalidation warning unless the sidebar is open](https://github.com/pixiebrix/pixiebrix-extension/blob/9fa424db8a60eb3419cf9b85a29fea8a9c9e63a7/src/contentScript/contentScriptCore.ts#L53-L53). So I might be misremembering the exact sequence of events on the call

## Actual behavior

- PixieBrix shows context invalidated error toast in the original tab

## Expected behavior

- PixieBrix only shows context invalidated toast if context being lost impacts PixieBrix behavior in the tab

## Desktop (please complete the following information):

- OS: Windows 
- Browser: Chrome
- Extension Version: 1.8.8

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/9fa424db8a60eb3419cf9b85a29fea8a9c9e63a7/src/errors/contextInvalidated.ts#L32-L32

**Comment by fregante** [comment]
We have a handful of `notifyContextInvalidated` calls, most of them handle the errors. So the notification is showing because an error is being thrown somewhere.

I've seen such errors appear when the content script was loading and the extension restarted, because it was messaging the background page. A quick solution for that would be something like:

```js
function notifyContextInvalidated() {
  if (content script has not finished loading) {
    return
  }
  …
```

I think this is safe because if the extension was restarted, then the user _will_ eventually see the expected mods on the page. This might not cover all scenarios though.

**Comment by fregante** [comment]
By the way, is reloading the extension still the best way to handle new data? Could this be done _reactively?_

https://github.com/search?q=repo:pixiebrix/pixiebrix-extension%2520/runtime.reload/&type=code

**Comment by twschiller** [comment]
> By the way, is reloading the extension still the best way to handle new data?

It's the easiest way to to ensure consistent behavior. In the case of extension version updates, I think it's the only way. In the case of extension "linking" to a new token, there's Dev Ex demand to remove the reload. However, we'd need to audit our use of authentication listeners to verify all the necessary operations get fired

**Comment by fregante** [comment]
For this specific issue, I think we should just not load the content script. This should be *as easy as* adding a storage check and not load contentScriptCore. If the user is not authenticated, I don’t think there's anything to do in the content script.

**Comment by twschiller** [comment]
>  If the user is not authenticated, I don’t think there's anything to do in the content script.

Correct - for the main content script there shouldn't be anything to do for unauthenticated users

**Comment by fregante** [comment]
This is what I'm presented with after clearing the token: the existing menu items are still added.


<img width="658" alt="Screenshot" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/a5fac37e-b429-43d0-87f9-7a0e334c5364">

Interesting the page editor and options page work too, except the `#/` entry point:

<img width="749" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/5d131063-6c65-4e64-b534-9368e2cf62b0">


As for this issue, I'm not able to replicate it (probably because I'm not following the "no teams" part). If you see it again, the console will probably contain the real error behind that notification. I only see errors in the console if I restart it too early:


https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/06fb0cc0-d4dd-40d8-9ece-32ca26f7b3e2





This epic fixed a lot of related issues with stuff being left behind/active, but there's probably more stuff to cover:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4258
