### ISSUE TITLE
MV3 support for custom browser action icon

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7622]
Context
---
* Due to time constraints, we did not solve for adding a custom sidebar icon in MV3 as part of the Custom Branding work.
* We still need to determine a solution and implement it before we finish the MV3 migration.
* https://github.com/pixiebrix/pixiebrix-extension/pull/7621

**Comment by twschiller** [comment]
@grahamlangford I updated the title to distinguish vs. customizing the title/icon show in the Chromium side panel dropdown

**Comment by twschiller** [comment]
FWIW, when I change the partner theme to `automation-anywhere` the existing SVG files doesn't work either:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/18c97f53-892c-495b-b27a-df2967d16d68)

**Comment by fregante** [comment]
I assume that's:

https://github.com/pixiebrix/pixiebrix-extension/blame/955a8a94accc90b1a7966bd4d481bd52148480c5/src/background/partnerTheme.ts#L37-L38

Which attempts to set the SVG directly instead of loading it first.

**Comment by fregante** [comment]
Early testing and [this StackOveflow answer](https://stackoverflow.com/a/69385604/288906) suggest that it's not possible at all to turn an SVG into ImageData in a worker. Because:

- there is no DOM in workers, so no `Image`/`document.createElement`
- `createImageBitmap` only supports SVG via `<SVG>` element, which cannot be created without DOM

So there doesn't seem to be a way to draw an SVG onto a canvas in service workers.

We do have access to `chrome.offscreen` though, so it should be possible (albeit quite verbose)

I'll check again after related work is done:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7632

**Comment by fregante** [comment]
So for reference:

1. `createImageBitmap` with SVG was rejected in 2018 https://issues.chromium.org/issues/41250699
2. another ticket was opened later and is still open https://issues.chromium.org/issues/41250701

So yeah `chrome.offscreen` is the only option:

1. create offscreen.html
2. create offscreen.js
3. figure out messaging (probably just postMessage because it can pass ImageData)
4. use it when the detected fileType is SVG

**Comment by twschiller** [comment]
We'll be accounting for file version on pixiebrix-app. Here's a skeleton spec describing considerations: https://www.notion.so/pixiebrix/Phase-support-custom-branding-MV3-browser-action-icon-f43f5cf790ed4776b15e23638f5ce580?pvs=4

IMO the complexity of file conversion in the extension isn't worth the benefit given that we're in control of the source format
