### ISSUE TITLE
Set Input Value brick clears whole page if DraftJS editor is empty

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7630]
## Describe the bug

Set Input Value brick for DraftJS editor clears the whole page

## To Reproduce

1. Visit https://draftjs.org/
2. In Page Editor, run a Set Input Value brick on `[contenteditable="true"]` with value "Foo"

## Actual behavior

Whole page is cleared

## Expected behavior

The text is added to the content editable

## Discussion

-  Doesn't occur if there's text in the content editable
- Likely cause by how the [document.execCommand("selectAll");](https://github.com/pixiebrix/pixiebrix-extension/blob/9179f057af48f585b1c03e8934591f3d9f53c9db/src/bricks/effects/forms.ts#L84-L84) call interacts with the page 

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: main

**Comment by fregante** [comment]
It's not due to `selectAll` but it appears to be a conflict with React and `insertText`. In that call, you can see React progressively remove all the elements on the page. Set this break point, it will break about 4 times:

<img width="568" alt="Screenshot 24" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f6a42999-5b2a-4403-9428-d91679948867">



Possible solution:

- https://stackoverflow.com/a/63643176/288906
- https://github.com/facebookarchive/draft-js/issues/616#issuecomment-426047799

**Comment by fregante** [comment]
I'll open a dedicated issue
