### ISSUE TITLE
Review getRootCause call sites to ensure handling of non-error data

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7687]
Context
---
- `getRootCause` and `selectSpecificError` are used to walk the `cause` chain to 
- That's relevant because we nest errors, e.g., with ContextError
- https://github.com/pixiebrix/pixiebrix-extension/pull/7681#discussion_r1499150288
- `cause` can hold hold arbitrary data, not just errors: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#providing_structured_data_as_the_error_cause
- We need to double check uses of `getRootCause` and `selectSpecificError` to ensure they conceptually make sense to receive a non-error
- I think we might need to introduce a version of `getRootCause` that stops once cause is not error-like
- Errors are often passed around as "unknown", so we won't get type checker errors. The symptom will be that meaningful error messages might be dropped and instead a generic error message will show because the cause is not error-like

**Comment by fregante** [comment]
> * We need to double check uses of `getRootCause`

Note that `getRootCause` is `@deprecated` and it's only used in 3 places:

https://github.com/pixiebrix/pixiebrix-extension/blob/95cef5f4b069cbbab02118a44cfef31592b90937/src/contrib/google/sheets/core/handleGoogleRequestRejection.ts#L45

This is fine, it expects Google's error at the root.

https://github.com/pixiebrix/pixiebrix-extension/blob/95cef5f4b069cbbab02118a44cfef31592b90937/src/errors/contextInvalidated.ts#L56

Also fine, it expects a context invalidated error at the root.

https://github.com/pixiebrix/pixiebrix-extension/blob/95cef5f4b069cbbab02118a44cfef31592b90937/src/components/documentBuilder/render/ButtonElement.tsx#L90-L92

This makes a wrong assumption about `hasSpecificErrorCause(error, SubmitPanelAction)`, but it's still ok as long as `SubmitPanelAction` doesn't take any `cause`. It should just be replaced with a single `selectSpecificError` call.




> * and `selectSpecificError` to ensure they conceptually make sense to receive a non-error

`selectSpecificError` will never select an error that doesn't match the specified Constructor, so it cannot return a non-error.


> * I think we might need to introduce a version of `getRootCause` that stops once cause is not error-like

I don’t think we need to because `getRootCause` isn't meant to be used directly (or at all)



> * Errors are often passed around as "unknown", so we won't get type checker errors. The symptom will be that meaningful error messages might be dropped and instead a generic error message will show because the cause is not error-like

I think this is based on the fear that we _extract and throw_ the `cause` of an error, but I don't see the evidence of it happening in the aforementioned helpers. 

As long as we never `throw {randomObject}` or `Promise.reject({randomObject})` that would rarely happen. We have a lint rule to protect us (https://eslint.org/docs/latest/rules/no-throw-literal), but external APIs aren't covered.
