### ISSUE TITLE
Add Playwright run to GitHub Actions

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7691]
* Update `.github/workflows/ci.yml` to run Playwright tests in GitHub Actions
* Need to add test user credentials to https://github.com/pixiebrix/pixiebrix-extension/settings/secrets/actions

**Comment by twschiller** [comment]
@fungairino @mnholtz see https://github.com/pixiebrix/pixiebrix-extension/issues/7880. I think we'll need to tweak the CI setup for dependabot

**Comment by mnholtz** [comment]
I think the final thing we're waiting on is e2e test flakiness due to the following errors:
- `ERR_BLOCKED_BY_CLIENT` errors when navigating to the extension console url, e.g. https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8270884192/job/22629433330
    - My hypothesis is that this is a race when we visit the extension console before it's been fully initialized in the browser 
- ` Error: page.goto: Target page, context or browser has been closed` which can be also seen in the second retry on https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8270884192/job/22629433330 and also locally sometimes
    - I'm wondering if installer.ts is opening the admin console page & interrupting the page context somehow?

**Comment by twschiller** [comment]
> I think the final thing we're waiting on is e2e test flakiness due to the following errors:

During the linking there's a reload - do we need to be just adding a pause to give it time to reload? You might also consider going to the Admin Console and clicking "Open Extension Console"

**Comment by mnholtz** [comment]
Another flakiness I noticed locally (which will probably also happen in CI) is the tests timeing out because the Extension Console taking forever to load.

**Comment by mnholtz** [comment]
Proposed fix is here: https://github.com/pixiebrix/pixiebrix-extension/pull/7914

**Comment by mnholtz** [comment]
We merged https://github.com/pixiebrix/pixiebrix-extension/pull/7914, let's observe for about 1/2 the day today to see if there are any other instances of flakiness, and then I propose we wrap up the GH action
