### ISSUE TITLE
Introduce "read form" and "set form" bricks

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7787]
The logic we have around input field extraction might be verbose for multiple fields and difficult to get right for checkboxes/radios.

I think it would be beneficial to add a brick (and maybe eventually replace the existing ones) to correctly read/write into the forms correctly and in a single pass.

Reading the values from a `form` is extremely easy thanks to the `FormData` API. Writing is a bit [less straightforward](https://github.com/sindresorhus/project-ideas/issues/137) but we already have duplicate code across the extension to do this in various ways.

The only problem/exception would be anything related to `contentEditable`, because that's not actually part of the form until a `submit` handler places it into a field according to its own logic.

Context:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7770#discussion_r1509311501

**Comment by twschiller** [comment]
For some additional context:
- Our form reader brick is here: https://github.com/pixiebrix/pixiebrix-extension/blob/22bc0cc0a7ed27edf47c83b4a7a2c61950cdc86f/src/bricks/transformers/FormData.ts#L34-L34. It currently uses JQuery to enumerate the inputs vs. using the FormData API
- Our form setting brick is here: https://github.com/pixiebrix/pixiebrix-extension/blob/22bc0cc0a7ed27edf47c83b4a7a2c61950cdc86f/src/bricks/effects/forms.ts#L181-L181

The gotchas with these two are:
- Because `form` is not a UI element, it's hard for users to select the form itself using our selector tool
- In the wild, a lot of forms are unfortunately missing `name`s on inputs. So you often end up having to using the Extract from Page and Set Value bricks
- In the wild, the FormData API doesn't work with forms in some frameworks (IIRC, Vue)

**Comment by fregante** [comment]
> * Because `form` is not a UI element, it's hard for users to select the form itself using our selector tool

Do bricks have to receive an exact reference to a form or could you, for example, select any field of the form and just extrapolate it from there?

We also have other solutions:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2508
- Traversing the DOM after selection (e.g. show all the parents, let the user pick what they intended to pick. We have something similar in the Document Builder)



> * In the wild, a lot of forms are unfortunately missing `name`s on inputs

Perhaps then "Extract from page" can continue to exist as a fallback:

1. Extract everything via "Form extractor"
2. Fill any gaps via "Extract from page", including JS editors/contenteditable



> * In the wild, the FormData API doesn't work with forms in some frameworks (IIRC, Vue)

Sounds strange, probably it's a repeat of "missing `name` attributes". If an `input` exists on the page _and_ it's inside a form, the API _can't cannot work_

**Comment by twschiller** [comment]
Closing - not on feature roadmap
