### ISSUE TITLE
Feature flag caching refresh policy/TTL too long

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#7806]
## Describe the bug

Feature flags enabled for a user are cached for too long (30 days). The user is currently required to log out and then back in to see newly updated feature flags. Instead we should refetch the feature flags on new session initialization every time.

We already fetch the `me` endpoint every time we restart the extension, so we should just update the cache with those updated values.

## Context
https://pixiebrix.slack.com/archives/C023KL47XV4/p1709567040170369

**Comment by twschiller** [comment]
There's also some issue with `useFlags` because it uses RTK Query to fetch flags. In https://github.com/pixiebrix/pixiebrix-extension/pull/7845 we had to add logic to await flags being ready

In the React world, we should potentially fetch the flags are part of RequireAuth to ensure descendents using useFlags have the up-to-date flags when they render

**Comment by twschiller** [comment]
There's already a call to reset the flags here when the module is loaded: https://github.com/pixiebrix/pixiebrix-extension/blob/3806eb0c7ac9b7c615dd91bbb950380f62fe51d2/src/auth/featureFlagStorage.ts#L60-L60

The downside is that: it will reset the flags so there is a period where no flags are set while waiting for the flags call to resolve
