### ISSUE TITLE
Interval triggers are disabled when the page editor is open

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7812]
## Describe the bug

It looks like "Interval" triggers are immediately stopped when the page editor is open. This feels like intentional behavior, but also it looks like the interval is not working at all.

## To Reproduce

1. Create trigger
2. Set "Interval" as trigger event and 500ms as interval
3. Add "Window alert" brick
4. Save it

## Actual behavior

Nothing happens unless I click "Run Trigger", at which point it only runs once

## Expected behavior

The interval should already start

## Screenshots/Loom

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/52558f04-2912-4b40-a430-da816848e0a0

## Desktop (please complete the following information):

- Extension Version: 1.8.11

## Related

Found while debugging:

- https://github.com/pixiebrix/pixiebrix-extension/issues/7774

**Comment by twschiller** [comment]
> It looks like "Interval" triggers are immediately stopped when the page editor is open. This feels like intentional behavior, but also it looks like the interval is not working at all.

Correct, the behavior is intentional. Otherwise, it's hard to debug interval triggers because either: 1) you have to wait for it to run, or 2) the trace keeps changing

The logic is here: https://github.com/pixiebrix/pixiebrix-extension/blob/aebd38095e88bf0520323431ea37761f9faa966e/src/contentScript/pageEditor/dynamic.ts#L106-L106

Agree we could make it clearer what's happening and/or provide a way to run it as an interval instead

**Comment by fregante** [comment]
This might be fixed by a message near the "Trigger type: Interval" dropdown:

> Interval triggers are not enabled while the page editor is open. Click "Run trigger" to run it once.
