### ISSUE TITLE
Insert at Cursor brick doesn't work sometimes from MV2 sidebar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7835]
## Describe the bug

- The fix in https://github.com/pixiebrix/pixiebrix-extension/pull/7827 sometimes doesn't work. Likely due to mouse movement patterns, or potentially if the user mouses into the sidebar to quickly?
- Observed by both @twschiller and @MMirandi on Zendesk on 1.8.10-beta.4 (Zendesk uses CKEditor without a frame). Works if you leave the sidebar to reselect the text and then mouse back into it

## Discussion

- Potentially, need to add a focus save when the sidebar is shown sidebarShowEvents to handle the case where the user has already mouseentered the sidebar: https://github.com/pixiebrix/pixiebrix-extension/blob/5df77606067da48fe8b438d60add8b9e98b2c2a0/src/contentScript/sidebarController.tsx#L549-L549

**Comment by fregante** [comment]
This definitely happens if you open the sidebar and move the cursor to it before it finishes loading (easy to do because the sidebar opens 10px below the button)

<img width="112" alt="Screenshot 4" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3b12cecb-2db6-4f7e-b98e-cddc97c7e6c9">
