### ISSUE TITLE
Text Selection Popover is sticky if target element is no longer visible

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7882]
## Describe the bug

Text Selection Popover moves to upper-left of screen in the element it's targeting no longer exists/is not visible. We should just hide the popover in that case

## To Reproduce

1. Select some text in the Gmail email composer
2. Close the the email composer

## Actual behavior

Text selection popover moves to the upper-left of the screen (0, 0) coordinates

## Expected behavior

Text selection popover hides/closes

## Desktop (please complete the following information):

- Extension Version: `main`

## Discussion

- On Google Docs, the popover just stays in the upper-left (I believe because Google Docs is using Canvas)

**Comment by fregante** [comment]
> * the popover just stays in the upper-left

I don't know if this is technically "hidden", I believe Google moves this field around so that the OS/browser knows where to show auto-complete information (etc), but then it just resets its position to 0,0 at some point. We very likely need some Google Docs-specific logic.

I think you can use IntersectionObserver and/or ResizeObserver to track:

- if the element is in the viewport
- if the element becomes "hidden" (e.g. `display: none`)

**Comment by fungairino** [comment]
I assume we want to tackle this behavior for the command popover as well, which stays on the screen even when the initial input is closed.
![Screenshot 2024-03-18 at 5 33 55 PM](https://github.com/pixiebrix/pixiebrix-extension/assets/3498063/a354c73b-a2e5-4a28-b7da-e1a0916d508c)
