### ISSUE TITLE
Improve error message from Insert Text at Cursor brick

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8063]
## User Story

As a PixieBrix mod developer, I want meaningful error messages for the Insert Text at Cursor brick in the Page Editor, so that I can debug errors myself

## Motivation

See: https://pixiebrix.slack.com/archives/C0436P48QHY/p1711401954499719

**Comment by twschiller** [comment]
Potential message: "Unable to insert text at cursor. Is there an active text editor?"

**Comment by fregante** [comment]
There's no original error, this is the result of execCommand returning false. This specifically happens when there's no field focused/selected or if the field is read-only. 

As seen in the last related PR, we generally don't try to get the selected/focused field before running execCommand unless necessary.

**Comment by twschiller** [comment]
> There's no original error, this is the result of execCommand returning false.

The "original error" is here: https://github.com/pixiebrix/pixiebrix-extension/blob/837ea111eead6afd0adec5c76cf8b628e220a5fb/src/contentScript/textEditorDom.ts#L72-L72. So we either need to change that error, or wrap it in `InsertAtCursorEffect`. I would wrap it and keep the error thrown by insertAtCursorWithCustomEditorSupport
