### ISSUE TITLE
AA Brick Configuration: If a mod contains more than one AA brick, the page editor breaks when different control room integrations are chosen on different bricks

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#8137]
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/2801308/eb5ecf75-22cc-4b33-a3cf-2e9a38d91575)

### Steps to Reproduce
1. Create a new mod component in the page editor
2. Add either one of the AA bricks (Run Bot, Run API Task)
3. Select a local integration config that is a control room user/pass login (not OAuth2)
4. Add another AA brick (either one again)
5. In the second brick, select an OAuth2 control room integration config option

The error is being thrown from [this spot in `useSanitizedIntegrationConfigFormikAdapter()`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/useSanitizedIntegrationConfigFormikAdapter.ts#L52-L54)

Updating the auth config when the auth widget selection is changed is handled by `setIntegrationAuthSelectionForField()`, which calls `produceExcludeUnusedDependencies()` [here](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx#L146).

Need to investigate why this isn't cleaning up the previous AA integration, when a new one is selected.

**Comment by twschiller** [comment]
> when different control room integrations are chosen on different bricks

Do we know the root cause? Under the hood, Page Editor should be implicitly creating 2 integration dependencies.

When it comes to activation, having multiple integrations of the same integration type isn't supported. 

So right now, this situation can only occur when the mod developer is in the process of switching over to a new integration definition. Perhaps we need a lint rule that warns if there are multiple configurations being used for the same integration definition?

**Comment by BLoe** [comment]
Sorry, I know what the issue is here I just didn't finish writing up the details for the fix. I posted the screen shot to keep track and make sure I didn't forget about it. Will be adding more here soon.

**Comment by twschiller** [comment]
Slack discussion clarifying specification: https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1713488907786029
