### ISSUE TITLE
MV3 open sidebar message dialog appears in frames when using Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8141]
## Describe the bug

MV3 open sidebar message appears in frames

## To Reproduce

1. https://pbx.vercel.app/advanced-fields/
2. Open Page Editor
3. Add a Sidebar Panel extension

## Actual behavior

Open sidebar dialog appears on top-level frame and in TinyMCE and CKEditor Frames

## Expected behavior

Open sidebar dialog should only appear on top-level frame

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/e5732d05-c728-4cf6-be4b-79c8e00a768b)

## Discussion/Diagnosis

- This might only impact the Page Editor because it attempts to run the mod in all frames? Even so, is the Page Editor messaging to open the sidebar? IIRC, our sidebar mod knows not to try to open the sidebar 

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/4668ee9455d97634a9512663bf0c80c04c7a91ef/src/utils/iframeUtils.ts#L22-L22
- https://github.com/pixiebrix/pixiebrix-extension/blob/4668ee9455d97634a9512663bf0c80c04c7a91ef/src/contentScript/sidebarController.tsx#L135-L135: @fregante the logic for showSidebar looks wrong? `focusCaptureDialog` should not be showing the dialog in the iframe. It it's running in a iframe, I think we just want the iframe to message the top-level frame. In that case, the iframe doesn't need to worry about focus because there's no focus change in the frame

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.12 mv3

**Comment by fregante** [comment]
This is the page editor attempting to auto-open the sidebar, right? I don't remember the exact logic, but I'm not sure why pageEditor's call is ending up in the frames to begin with, the page editor can open the sidePanel directly.

I think I might have missed this specific call when migrating. The solution should be to open the sidepanel directly from the page editor



> * the logic for showSidebar looks wrong?

It comes from this PR and it was meant to target MV2:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7490

The logic is unrelated here since `isMV3` is true already.

**Comment by fregante** [comment]
> * It it's running in a iframe, I think we just want the iframe to message the top-level frame

I think that the logic should be simplified further:

1. the content script has to ask the background page to open the side panel anyway
2. as part of this call, if it fails, the background page should message the TOP_FRAME to show the modal

Otherwise the call would look kinda messy:

1. iframe asks background to open the sidebar
2. background fails
3. iframe asks background to forward "show modal" to the TOP_FRAME
4. TOP_FRAME handles the message and shows modal
5. then TOP_FRAME messages the background page to open the sidebar

**Comment by twschiller** [comment]
@fregante thanks for digging into this - do you have availability to work on the fix/adjustment?

> but I'm not sure why pageEditor's call is ending up in the frames to begin with

It would be related to one of the following
- https://github.com/pixiebrix/pixiebrix-extension/blob/4668ee9455d97634a9512663bf0c80c04c7a91ef/src/pageEditor/toolbar/ReloadToolbar.tsx#L100-L100
- https://github.com/pixiebrix/pixiebrix-extension/blob/4668ee9455d97634a9512663bf0c80c04c7a91ef/src/pageEditor/sidebar/ActivatedModComponentListItem.tsx#L118-L118

**Comment by fregante** [comment]
It seems to be this call:

https://github.com/pixiebrix/pixiebrix-extension/blob/4668ee9455d97634a9512663bf0c80c04c7a91ef/src/contentScript/pageEditor/dynamic.ts#L135

That line should probably be removed from there and added as a click handler to:

- "Render Panel"
- the extension list/sidebar in the pageEditor

> do you have availability to work on the fix/adjustment

If you can wait 24 hours yes.
