### ISSUE TITLE
Fix/update All URLs site pattern to match `about:srcdoc` iframes

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8170]
Context
---
- `*://*` only matches http/https URLs
- Some iframes use `srcdoc` so have a `about:srcdoc` URL
- `<all_urls>` is a special match pattern to match any URL with a permitted scheme https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns. For the purposes of running mods, we treat it as matching `about:srcdoc`: https://github.com/pixiebrix/pixiebrix-extension/blob/733719b0a8f55f9f3160b0279b09a103714edc36/src/bricks/available.ts#L25-L25
- Chrome's contextMenu API also supports `<all_urls>` for [documentUrlPatterns](https://developer.chrome.com/docs/extensions/reference/api/contextMenus#:~:text=%5B%27page%27%5D.-,documentUrlPatterns,-string%5B%5D%C2%A0optional)
- By and large, all of our uses of `*://*/*` that aren't for sidebar should actually be `<all_urls>` (e.g., context menu, snippets, etc.). It's safe to have the site pattern be that for sidebars too though

Discussion/Open Questions
---
- Are there some site/permissions contexts where `<all_urls>` is not a valid value?
- Ideally, end users should not have to think about the distinction between `<all_urls>` and `*://*/*`
- Does `*://*/*` match iframes when passed as a documentUrlPattern for context menus?

Options
---
- Change our All URLs shortcut to use `<all_url>`
- Change the `*://*` match pattern to specially handle `about:srcdoc`: https://github.com/pixiebrix/pixiebrix-extension/blob/b2b87d2331155b25c58b155891d12a3f2ad54f76/src/bricks/available.ts#L31-L31

**Comment by fregante** [comment]
Some context: https://github.com/fregante/webext-patterns/issues/13

In short:

- the content script is not injected into `<all_urls>`: https://github.com/pixiebrix/pixiebrix-extension/blob/b2b87d2331155b25c58b155891d12a3f2ad54f76/src/manifest.json#L24
- I think the browser still injects it into `about:srcdoc` because it inherits the parent's host (it matches the frame **without matching its URL**): https://developer.chrome.com/docs/extensions/develop/concepts/content-scripts#injecting-in-related-frames


For the browser's purposes `*://*/*` differs from `all_urls` **exclusively** because it also matches `file:`. As a global permission it's only needed for screenshotting tabs, but that's unrelated to content scripts, it just needs to be part of the manifest's `host_permissions` and that's it.


The `srcdoc` semantic is only something that PB currently adds:

https://github.com/pixiebrix/pixiebrix-extension/blob/b2b87d2331155b25c58b155891d12a3f2ad54f76/src/bricks/available.ts#L29-L32

Now from the user's perspective, I'd:

- drop the `https://*/*` shortcut
- leave `*://*/*` as is

I think adding `<all_urls>` can only add confusion because it's not a pattern and users have to match it exactly (not `all_urls`, not `(all_urls)`, not `<allurls>`, etc)

**Comment by twschiller** [comment]
Thanks for the writeup, I've updated the issue description to clarify the other option. For me, I think a deciding factor would be consistency with the native documentUrlPatterns behavior.

> I think adding <all_urls> can only add confusion because it's not a pattern and users have to match it exactly (not all_urls, not (all_urls), not <allurls>, etc)

I agree it's not ideal. Although, I generally wouldn't expect users to have to write it, and we could always apply validation to ensure the user is providing a valid match pattern
