### ISSUE TITLE
NPE activating deployments from Extension Console modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8645]
Context
---
- Slack discussion: https://pixiebrix.slack.com/archives/C023KL47XV4/p1718730515237629

Steps to Reproduce
---
1. Deactivate a deployment
2. Refresh extension console
3. Click "Activate" button in the modal

Discussion
---
- Error caught at: https://github.com/pixiebrix/pixiebrix-extension/blob/a9d45b940d51b0899fbcbcba950bce94b05db5f2/src/extensionConsole/pages/deployments/DeploymentsContext.tsx#L252-L252
- Error thrown at: https://github.com/pixiebrix/pixiebrix-extension/blob/a9d45b940d51b0899fbcbcba950bce94b05db5f2/src/extensionConsole/pages/deployments/activateDeployments.ts#L59-L59

Screenshot
---

<img width="571" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/93c570dd-6f23-4f12-8bdf-5e3ebf484e35">

Version
---
- 2.0.3-beta.1

**Comment by fungairino** [comment]
What's interesting is that I downgraded webpack manually and ran `npm i`, rebuilt the prod built, but the bug was still present.

This eventually led me to write a new e2e test and script to bisect the issue
```
npm ci && npm run build
cd ../../pixiebrix-extension
CI=1 npm run test:e2e -- --project=chrome deployments
```

The bisect still pointed the webpack bump as the culprit, so most likely some of the downstream dependencies that were updated/changed are the culprit:

"acorn-import-assertions": "^1.9.0", -> "acorn-import-attributes": "^1.9.5",
"enhanced-resolve": "^5.16.0", -> "enhanced-resolve": "^5.17.0",
