### ISSUE TITLE
Sidebar gets stuck in "connecting to page" state

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8651]
Context
---
- See Zendesk ticket for screenshots/context: https://pixiebrix.zendesk.com/agent/tickets/581
- Impacting 1 user/application: https://app.pixiebrix.com/support/user/143d0c94-13ee-4a24-bd04-cdf9b2d99b7c/?tabKey=exportables
  - No business errors in support console
-  > The TM also tried to re-download the mod but he's getting the same issue.
- User is on 2.0.2 build of the extension

Investigation
---
- Related Datadog errors:
  - Cannot access contents of the page. Extension manifest must request permission to access the respective host.
  - The Sidebar took too long to load. Retry your last action or reopen the Sidebar
  - The iframe did not load within 3 seconds: chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/sandbox.html
- Looks like the content script is not initializing properly for the user on the page

Discussion
---
- If it's a permission issue, after a certain period of time, we could have the sidebar check to see if PixieBrix has permission to access the page?

Screenshots
---
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/24e2f396-cdac-4452-ad52-7e1d4c3193fd)

**Comment by twschiller** [comment]
@fungairino any quick ideas for what telemetry we'd want to look at to help diagnose?

**Comment by fungairino** [comment]
RUM logs for this user: [link](https://app.datadoghq.com/logs?query=service%3Apixiebrix-browser-extension%20%40usr.email%3Aedward.garcia%40supportninja.com%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZBKlx4dAADh-9ovrc2VrQAB&dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3Aall%29%2Cversion%3A%210%29&env=production&errors=qson%3A%28data%3A%28issueSort%3ATOTAL_COUNT%2CtopN%3A%215%29%2Cversion%3A%211%29&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&logs=qson%3A%28data%3A%28indexes%3A%5B%5D%29%2Cversion%3A%210%29&messageDisplay=inline&name=browser.request&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&refresh_mode=sliding&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%2110%29%2Cversion%3A%211%29&service=pixiebrix-browser-extension&storage=hot&stream_sort=time%2Cdesc&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&view=spans&viz=&from_ts=1717942884718&start=1719235161248&end=1719238761248&to_ts=1719238884718&live=true&paused=false)

**Comment by fungairino** [comment]
My working hypothesis is that for some reason a pb script is failing to be injected due to the tab not having a url yet.

The following error is logged:
```
Cannot access contents of the page. Extension manifest must request permission to access the respective host.
```

And although pixiebrix requests permission for all urls, this could still happen when injecting into a tab that was just created via chrome.tabs.create or navigated via chrome.tabs.update or inside chrome.tabs.onUpdated listener when tab only starts loading. 

Looking to see if we can resolve by following this suggestion and add a check to ensure the url is present on the tab.
https://stackoverflow.com/a/67244340

**Comment by fungairino** [comment]
I'm not sure how to reproduce the issue, but the only place in code where it would make sense for this to happen is this function in the background script:

https://github.com/pixiebrix/pixiebrix-extension/blob/d01a51959b9839bbf2a62e7e3406c7082675ffa2/src/background/tabs.ts#L57

It might be as simple as just adding a check there for the tab url to be present.

**Comment by fungairino** [comment]
Looking at when the error occurs a bit more closely, it only should happen when the extension tries to execute a script.
https://chromium.googlesource.com/chromium/src/+/9a2acf7c14990afb4b0e5d503194ab092322525d/chrome/common/extensions/permissions/permissions_data.cc#533

Theoretically this should only occur when we are trying to inject into a tab recently loaded by or `chrome.tabs.create` `chrome.tabs.update, but I don't think I see any instances in our code where we do this.

@twschiller any ideas?

I think at this point we need a bit more info on how to reproduce this issue / have a chat with the affected customer. Potentially look into improving our error telemetry further to tell what was the actual source error that caused this (since the thrown error does not have a stack trace).

For reference, here is a datadog query showing how often this error happens:

https://app.datadoghq.com/logs?query=service%3Apixiebrix-browser-extension%20env%3Aproduction%20%22Cannot%20access%20contents%20of%20the%20page.%20Extension%20manifest%20must%20request%20permission%20to%20access%20the%20respective%20host.%22%20status%3Aerror%20%22cannot%20access%20contents%20of%20the%20page%20extension%20manifest%20must%20request%20permission%20to%20access%20the%20respective%20host%22%20&agg_m=count&agg_m_source=base&agg_q=%40usr.email&agg_q_source=base&agg_t=count&cols=host%2Cservice&fromUser=false&messageDisplay=inline&refresh_mode=sliding&step=%7B%22type%22%3A%22week%22%7D&storage=hot&stream_sort=desc&top_n=10&top_o=top&viz=toplist&x_missing=true&from_ts=1717962401515&to_ts=1719258401515&live=true

**Comment by twschiller** [comment]
I'd recommend we try to grab some time with the affected user. If it's a persistent problem for them and not a problem their co-workers, there is something likely different about their environment. @mthek10 can help coordinate time with the customer

cc @grahamlangford

**Comment by fungairino** [comment]
https://pixiebrix.zendesk.com/agent/tickets/581
