### ISSUE TITLE
Fix error root cause filtering

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#918]
**Actual behavior**
- Exceptions are being reported to Rollbar as errors regardless of whether they have a application, business, or cancel root cause

**Expected behavior**
- Cancellations should not be reported to rollbar
- Business errors should only be reported to rollbar for deployments/enterprise

**Triaging**
- Medium/high priority: since it's impacting our error notifications for devops

**Comment by fregante** [comment]
Is this due to a recent change?

One thing I noticed in https://github.com/pixiebrix/pixiebrix-extension/commit/9c1a283ecf80e813bc4cc33b01d508ad5a79da4b#diff-b11cc23a2fba4eea9f93e4576c1631198fa77b3795b61db13e016a4b15ef70f0R28 is that `reportError` receives an `ErrorEvent` but I'm not sure whether this event is actually supported. So maybe the function receives the object and just serializes it full instead of parsing out the actual `Error`
