### ISSUE TITLE
Page Editor - mods missing options they should have and have options they shouldn't

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#9374]
## Describe the bug

When I view a mod's input options in the Page Editor, the options may or may not be filled in. When I try to access mod options in a brick, I see mod options for other mods and may not see the options that should be available

## To Reproduce

1. Open the Page Editor
2. Select various mods with mod options
3. View their Mod Input Options
4. Attempt to access their options in a brick

## Actual behavior

- One or more of the mod options may be empty
- The brick may have access to options it shouldn't or be missing the options it should

## Expected behavior

- The mod options should be filled in with the same options the mod was activated with
- The brick should only have access to options for its own mod

## Screenshots/Loom

<img width="1981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMko4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56b027089bea1130f67b9cce2ffd04963fbbc786/image.png" alt="image.png" />

**Options available to the cache brick in ChatGPT sidebar**

<img width="610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlI4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0592b715335989a6e4c470c0879ffc07d2d576d2/image.png" alt="image.png" />

## Desktop (please complete the following information):

- Extension Version: 2.1.7-alpha.0 (main)

**Comment by twschiller** [comment]
Is there a chance this was leftover from the bug fixed here?: https://github.com/pixiebrix/pixiebrix-extension/pull/9359/files#diff-4d75e33c7ac04fdb6a31af40d8d0ae9c568208c208a8f8db6508eb85a3755b84L490. That bug could have caused options args from all mod components to be applied to that mod

I am seeing a bug where the Mod Inputs tab is switching back to the Metadata tab because the editor key is changing because the Page Editor is now updating the sequence number. I'll log a separate bug for that: https://github.com/pixiebrix/pixiebrix-extension/blob/d25e4c0ee9aa592439fe547f4b0a85f092a00426/src/pageEditor/panes/ModEditorPane.tsx#L47-L47

**Comment by grahamlangford** [comment]
> Is there a chance this was leftover from the bug fixed here?: https://github.com/pixiebrix/pixiebrix-extension/pull/9359/files#diff-4d75e33c7ac04fdb6a31af40d8d0ae9c568208c208a8f8db6508eb85a3755b84L490. That bug could have caused options args from all mod components to be applied to that mod

Looks like you're right. I reactivated the mod and can no longer reproduce
