### ISSUE TITLE
Regression: content script intermittently fails to load

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9411]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1730750267805279

**Comment by fungairino** [comment]
I tested a quick hack and this seems to avoid the reported error:

```
let tabDataStatus = 
// The background pages don't have a tab
isBackground() || location.pathname === "/offscreen.html" ? "not-needed" : "needed";
```

https://github.com/pixiebrix/webext-messenger/blob/94cc22cbac09b53d2b123f8be36fe78485c6a9ea/source/thisTarget.ts#L42-L43

However I think there are other issues that arises from this. This doesn't seem like it has an easy fix and the cause is probably due to web-ext messenger not properly supporting the offscreen page as a target.

Submitting a revert so we can unblock this issue quickly.
