### ISSUE TITLE
[Spike] Can the Sidebar appear on the left side of the browser?

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9427]
## Motivation
We're looking to improve starter mods and drive adoption. Is it possible for the sidebar to be pinned on the left side instead of the right side of the browser?

This could be useful for users whose workflows tend to aggregate on the left side of the window. 

## Acceptance Criteria

- [ ] T shirt sizing on implementation, and high-level steps / constraints / unknowns are mapped out

## Timebox
_4 hours_

**Comment by grahamlangford** [comment]
It's a browser setting: https://support.google.com/chrome/answer/13156494?hl=en#zippy=%2Cmanage-side-panel

I'm not sure if there's anything we can do on our side. I doubt it since it's a shared resource, but we can look into it. Likely those users' organizations would need to push that setting down

**Comment by Pashaminkovsky** [comment]
Yep that's sufficient info, thanks Graham
