### ISSUE TITLE
TypeError loading page script 

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#943]
I'm seeing this pop up again. Previously I had seen it during QA of an RC: https://github.com/pixiebrix/pixiebrix-extension/issues/722

Steps to reproduce:
* Visit when PixieBrix has page permissions: https://www.cbssports.com/fantasy/football/players/2258303/aj-brown/

```
ember.ts:248 Uncaught TypeError: (0 , lodash__WEBPACK_IMPORTED_MODULE_0__.unary) is not a function
    at Module../src/frameworks/contrib/ember.ts (ember.ts:248)
    at __webpack_require__ (bootstrap:19)
    at Module../src/frameworks/adapters.ts (errors.ts:223)
    at __webpack_require__ (bootstrap:19)
    at script.js:38535
    at script.ts:306
    at script.ts:306
```

Also potentially related (error being thrown on the host page). This error does not appear if you visit the page in incognito mode (without PixieBrix active)

```
Uncaught Error: Mismatched anonymous define() module: function() {
      return _;
    }
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require-2.3.5.js:1)
    at D (require-2.3.5.js:1)
    at require-2.3.5.js:1
    at nrWrapper ((index):5)
```

Related: 
* The custom webpack target we're using: https://github.com/awesome-webextension/webpack-target-webextension/tree/master/lib/webpack5
* https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkschunks

**Comment by fregante** [comment]
The other issue doesn't look like it's coming from us since it's `define`/require.js-based

**Comment by twschiller** [comment]
I'm pretty sure it's related. If I revoke access from the page and load it without PixieBrix having access, I don't see the error

I suspect by loading the page script, webpack's infrastructure code is setting some globals on window which interfere with the page's code

**Comment by fregante** [comment]
I found the problem. Lodash looks for a `define` variable first. On that website it exists, so it uses `define()` instead of `module.exports`, which instead remains the default `{}` and _all_ the `lodash` exports fail.

Switching to `lodash-es` certainly fixes this instance, but I wonder if we should look into fixing the root problem. Normally `define` is _also_ internally set by Webpack but our configuration disables AMD so that is left untouched.

A possible solution would be to use the `DefinePlugin` to override the any `define` calls in the bundle.
