### ISSUE TITLE
Background page is not automatically reloaded 

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#945]

**Comment by fregante** [comment]
Yes it is? That's the only part that can be reloaded by web-ext.

**Comment by fregante** [comment]
It seems that if you manually reload the extension a few times, web-ext might stop reloading the extension correctly. Or maybe it just stops after a while (maybe due to the system going to sleep, etc)

Also to clarify, `npm run watch` does not actually load nor reload the extension. That needs to be done via `web-ext run`, separately.

**Comment by fregante** [comment]
Tentatively assigning this to myself so I can look into this at some point

**Comment by fregante** [comment]
@twschiller is there any situation where an automated reload isn't also followed by a manual reload of the current context? In practice it feels like our current auto-reload only adds grief¹ since the views aren't updated.

I'm [looking into HMR](https://github.com/awesome-webextension/webpack-target-webextension/issues/29#issuecomment-1024339697) but some conflict seems to break it.

What if we add a global shortcut and/or add a double-click listener to the browser action?

<sup>1. It requires a [double-reload](https://github.com/pixiebrix/pixiebrix-extension/pull/618), it automatically breaks the editor because "Context invalidated", it [occasionally completely fails](https://github.com/pixiebrix/pixiebrix-extension/pull/2089), it closes `chrome-extension://` tabs, …

**Comment by fregante** [comment]
I think I've seen this behavior when you're looking at the background console. It seems that maybe the browser silently ignores the request or fails the reload.

**Comment by fregante** [comment]
Staled out.

This is a `web-ext run` reload issue:


- https://github.com/mozilla/web-ext/issues/2277

and we're moving away auto-reloading the whole extension anyway:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7598
