### ISSUE TITLE
Chrome storing old copies of extension

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#978]
**Context**
- Chrome appears to be keeping old copies of our extension around. Is there a setting we can change to adjust this?
- See https://twitter.com/yoz/status/1422681135025246209?s=20

**Comment by yozlet** [comment]
Thanks for checking this out! I wrote the tweet linked above. Happy to do further investigation if needed.

**Comment by fregante** [comment]
I wouldn't imagine them offering a way/API to clean itself up, it's just how the browser behaves. I can look into chrome's source but I feel I wouldn't find a solution there, let me know if I should.

**Comment by twschiller** [comment]
I'll go ahead an file a bug on the Chrome bug tracker: https://bugs.chromium.org/

**Comment by yozlet** [comment]
I've looked through my other extension folders and I can't find any that keep more than one old version. For some reason, PixieBrix had at least twenty versions. I only noticed the problem when doing a DaisyDisk scan of my HD, and found the PixieBrix extension folder taking up considerably more space than any other extension.

**Comment by yozlet** [comment]
Apologies: on further inspection, there are other extension folders with loads of old versions in. I don't know if it's because those are the only ones which have updated while I've had this Chrome install, or if other extensions are able to clean themselves up.

**Comment by fregante** [comment]
It looks like a very old bug: http://googlesystem.blogspot.com/2014/01/chrome-doesnt-delete-old-extension.html

They even made the reported bug private: https://bugs.chromium.org/p/chromium/issues/detail?id=329943

And someone commented "Expected behavior" on the latest report 😰 https://bugs.chromium.org/p/chromium/issues/detail?id=1121631

**Comment by yozlet** [comment]
The other alternative is to take on the whole other problem of shrinking the extension size. It's the biggest extension I use in terms of data size, and most of it is taken up by JS files and their source maps. Not sure what you could do with the JS, but the source maps should be dropped since there's no point shipping them without the original source code.

**Comment by fregante** [comment]
> shrinking the extension size

We're always working towards that. I wonder if this is a factor that enables this bug in Chrome. The blog post linked above is also about another large extension (56MB Google Photos extension)

**Comment by twschiller** [comment]
> Not sure what you could do with the JS, but the source maps should be dropped since there's no point shipping them without the original source code.

The Chrome Web Store doesn't allow you to upload source maps separate from the bundle. I'm not sure how removing source maps would affect the review process/times. We can definitely try to explore this with the Chrome team

IIRC the main culprits are:
- The contentScript etc. includes unused code due to coupling introduced by our messaging abstraction (we will be fixing this)
- The icon bundle: we could shift to fetching them from a CDN on demand
- jq: the module is compiled web assembly. The jq brick is an essential for data transformation in bricks. Since Chrome is banning remote code, we can't host it on a CDN
- Source maps (see explanation above)

**Comment by twschiller** [comment]
Closing since the impact will be mitigated by the messenger and other work we're doing on reducing build size
