### ISSUE TITLE
RFC: CSS/Styling architecture and design patterns

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#985]
**Context**
- Our codebase uses a variety of different conventions/approaches depending on what mood I was in when I wrote it: bootstrap, BEM, utility classes, inline `style` props, etc.
- We need to move to a common approach/design system as we scale the team/application
- It's too hard to track the intent behind styles and where they're coming from
- It's too easy to modify a style in a way that break other UI in a way you're not aware of

**Some Options**
- BEM
- CSS modules
- CSS in JS
- Emotion

**Considerations**
- Performance
- Maintainability

**Related Discussion**
- https://github.com/pixiebrix/pixiebrix-extension/pull/983#discussion_r682251638

**Comment by BALEHOK** [comment]
I'd say BEM is the least favorable option because it quickly becomes hard to maintain.

CSS in JS ([JSS](https://cssinjs.org/react-jss/?v=v10.7.1), Emotion) is a powerful solution. It brings an easier sharing of style values between JS code and styles. Yet many find it unreasonable to mix what you render and how you want to render it in the same file (JSX + styles).

CSS modules solve the problem of class names collisions. SCSS is a super powerful framework. CSS modules and SCSS have proven their reliability in production. CSS modules are already in use on the project. I would just keep using them and refactor other styles bit by bit.

CSS in JSS would be my second option. Adopting it would mean a slightly different approach to component authoring (we don't want to end up with 500-lines files).

BEM, I don't think it works well (in terms of maintainability and support) for large projects.

**Comment by BLoe** [comment]
I don't have the depth of JS/React experience to draw from, but coming from full-stack/framework dev and mobile, I pretty much agree with what @BALEHOK here. To me, it seems like CSS modules is the best option for what we need.

BEM seems like a quick method for simple projects, but seems like it would be pretty hard to gracefully scale the "rules" up to larger, professional projects. Seems like it has plenty of room for foot-guns if we're just telling people to name things a certain way and hope everything works out.

I am not a fan of combining content and styles into the same files. In my opinion it's messy and error-prone. I know some people like to have everything in one place, and it seems like it makes it slightly easier to work on and tweak individual components, but I think the downsides outweigh the benefits. With the styles in SCSS in separate files, it reduces code churn when changing styling, allows better organization and structure to the overall project styling, and allows technically-minded designers to interact directly with the styling code without worrying about affecting the content.

It also seems like CSS-in-JS would make theming, even a simple dark mode, very difficult. But I don't know if my instinct on that is correct or not. I wouldn't want to see a bunch of different themed CSS all combined into the JS file.

I set up CSS modules in PR #1059, along with a standardized folder/file structure for components going forward (also open to feedback on that if anyone has strong opinions there).

**Comment by twschiller** [comment]
I agree, let's proceed with gradually shifting toward CSS modules

**Comment by BALEHOK** [comment]
Awesome! Thanks @BLoe for your input.

100% for the Boy Scout Rule!

**Comment by BALEHOK** [comment]
A few of suggestions from the top of my head:
1. File with styles gets the same name as component's file + `module`. For instance: `ExtensionGroup.tsx` - `ExtensionGroup.module.scss`.
2. If the topmost element of a component needs a class, it's named `.root`. Just for consistency. Very often the root element doesn't have a semantic meaning that leads to all kinds of names like `.container`, `.wrapper`, `.holder`, or a name that mirrors the name of the component, then when you rename a component you have to rename the class.
2. Use simple class names, don't include component name (`.title` for the element that renders title in Extension Card component rather than `.extensionCardTitle`).
3. Favor flat structure of styles, use nesting only when required (
```
.root {...}
.title {...}
```
rather than
```
.root {
 ...

 .title {
  ...
 }
}
```

**Comment by BLoe** [comment]
>File with styles gets the same name as component's file + module. For instance: ExtensionGroup.tsx - ExtensionGroup.module.scss.

Yep, agreed. One note here is that I set up CSS modules so that it *only* picks up files with the `.module.scss` suffix, so that is actually required for this to work right now.

I'm cool with #2-4 also, makes sense to me.

**Comment by BLoe** [comment]
@twschiller Is there somewhere specific in Notion that it would make sense to document the decisions in this issue? Are we ready to close this out since it seems like we're all in agreement at this point?

**Comment by fregante** [comment]
_Continuing from https://github.com/pixiebrix/pixiebrix-extension/pull/2076#issuecomment-990052071_

> > I saw "Don't use bootstrap styling" in a couple places
> 
> Yeah, we were trying to mostly move away from bootstrap at one point. 

While I never liked Bootstrap, I think leaving Bootstrap is an expensive idea at this point:

1. Without a framework, each component is standalone and implements each style differently and incompletely.
	- One small example is the "collapse sidebar" button in the page editor: It does not have an `:active` style nor a `:focus` style, both of which come for free with `.btn` if I remember correctly. For this reason it feels alien from the rest of the UI.
2. _Dropping Bootstrap_ (even if over the course of months) means changing every single existing component, which time-consuming and IMHO has limited benefit, unless we find an equally-mature framework as a replacement.
3. If the intention is to find another framework, we should find one now and build on top of it as soon as possible, to avoid reimplementing the same "`<button>` reset" in every component

In a way it's easier to write simple CSS-in-JS for each component because we never have to look at which pre-existing style we can reuse, but this has long-term disadvantages. 

My suggestion is to style as much as possible with Bootstrap and only then complement it with CSS-in-JS.


The only drawback I see is that it potentially needs `className={cx('btn', style.insert)}` instead of `className={style.insert}`, but there's also a chance of it needing `className="btn-primary"` in some cases 💯 

---

That said, **this only generally applies to actual components like forms and buttons**, while utility functions like `ml-2` are indeed less useful in this context.

**Comment by BLoe** [comment]
> That said, **this only generally applies to actual components like forms and buttons**, while utility functions like `ml-2` are indeed less useful in this context.

Yeah, I agree here. Can we just use the React-Bootstrap `<Button/>` component as opposed to adding the CSS class?

**Comment by fregante** [comment]
I think this is resolved for now. This PR updates the previous non-module CSS usage:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2704
